### ISSUE TITLE
pip install python-sat[pblib,aiger] - no matches found

### ISSUE THREAD

**Issue by znittzel** [pysathq/pysat#100]
This problem is probably trivial, but if more people like me gets it, here's the solution.

When executing `pip install python-sat[pblib,aiger]` in mac os terminal using zsh, there's an error "no matches found".
 The solution is to put `python-sat[pblib,aiger]` in single-quotes like `pip install 'python-sat[pblib,aiger]'`

**Comment by alexeyignatiev** [comment]
Thank you, @znittzel. I added a note on the installation page.
