### ISSUE TITLE
Small bug with OptUx

### ISSUE THREAD

**Issue by vstylianos** [pysathq/pysat#101]
Hello Alexey. Thanks a lot for the wonderful library!

It appears that there is a small bug with the mus enumeration procedure of OptUx and I cannot figure out why yet. Let me explain:

If the formula contains only one mus, while it computes it, it throws the following error instead of exiting normally:

```
 if self.levl >= len(self.blop):
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

However, if the formula contains more than one mus then it enumerates all and exits normally.

I'm just trying to understand why is that. I'm using PySAT 0.1.7 on Python 3.7 and Mac OS.

**Comment by alexeyignatiev** [comment]
Hi @vstylianos,

Thank you for reporting! As far as I can see, the issue appears on the side of the MaxSAT solver, concretely it seems to be related to stratification. Does it occur given any formula with a single MUS?

**Comment by alexeyignatiev** [comment]
Hi @vstylianos,

I made an attempt to fix this issue [here](https://github.com/pysathq/pysat/commit/43fbe26674adfeb8051cd890a7fc309c0eb375ca). Please check.

**Comment by vstylianos** [comment]
Thanks for the very quick reply and fix. It is working now. Wonderful!
