### ISSUE TITLE
Having issue with C++ library while installing pysat via pip

### ISSUE THREAD

**Issue by Miaozxje** [pysathq/pysat#106]
I tried to install pysat and this error came out and I don't know what's the problem
I had tried to install some older MSVC build-tools but that aren't so helpful.

pycard.cc
      cardenc/pycard.cc(12): fatal error C1083: Cannot open include file: 'signal.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' 
failed with exit code 2

Can you guys direct me to solve this problem ? Thanks

**Comment by alexeyignatiev** [comment]
Hi @Miaozxje,

As I don't have access to a Windows machine, it may be easier to precompile the right version for your system by updating the build scripts for AppVeyor. This is how the toolkit is currently compiled for Windows. Which system are you using?

Alexey

**Comment by Miaozxje** [comment]
![image](https://user-images.githubusercontent.com/72405743/157804411-fc5322cb-f5e1-484b-9578-0bc2b671702a.png)
This is my windows version

**Comment by alexeyignatiev** [comment]
I meant not only the OS version but also Python. Because we have precompiled binary wheels for Python 3.6-3.9 on Windows x86-64. You may even want to try one of these versions to see if PySAT works.

**Comment by Miaozxje** [comment]
Okay thanks
