### ISSUE TITLE
pip install python-sat in Windows 10 x64 does not work

### ISSUE THREAD

**Issue by danieljmg** [pysathq/pysat#107]
Hello,
When trying to install it, I get a bunch of errors. I'd say the sources are:
cl : command line warning D9002 : omitted unknown option '-std=c++11'
      IncSimplePBConstraint.cpp
      C:\Users\X\AppData\Local\Temp\pip-install-pcgjh1ve\pypblib_b0bce726bee7414ba8752e623dbb82cc\External\pblib\pbconstraint.h(53): error C2059: syntax error: 'constante'
      C:\Users\X\AppData\Local\Temp\pip-install-pcgjh1ve\pypblib_b0bce726bee7414ba8752e623dbb82cc\External\pblib\pbconstraint.h(54): error C2059: syntax error: 'constante'
      C:\Users\X\AppData\Local\Temp\pip-install-pcgjh1ve\pypblib_b0bce726bee7414ba8752e623dbb82cc\External\pblib\pbconstraint.h(55): error C2059: syntax error: 'constante'
      C:\Users\X\AppData\Local\Temp\pip-install-pcgjh1ve\pypblib_b0bce726bee7414ba8752e623dbb82cc\External\pblib\SimplePBConstraint.h(29): error C2059: syntax error: 'constante'
      C:\Users\X\AppData\Local\Temp\pip-install-pcgjh1ve\pypblib_b0bce726bee7414ba8752e623dbb82cc\External\pblib\SimplePBConstraint.h(30): error C2059: syntax error: 'constante'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pypblib

Thank you,

**Comment by alexeyignatiev** [comment]
At this point, I can recommend trying one of the Python versions that are supported by our binary wheels already compiled for you: 3.6-3.9.
