### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by mueller55** [pysathq/pysat#109]
I spent several hours today trying to install pysat on Windows 10. Using the Windows shell and the VS2019 compiler, I first get the "Usage" output for wsl.exe 13 times, so once for each solver. This does not seem to be a problem per se, but might be a symptom of another problem. 

Later, the build fails; the first error is:
c:\svn\mueller_peter\GymInf\pysat-master\solvers\cadical\file.hpp(96): error C3861: 'getc_unlocked': identifier not found

Changing setup.py to use the option -std=gnu++11, as described in issue #93 (https://github.com/pysathq/pysat/issues/93) does NOT change this behavior (also, I am not using cygwin here - I also tried that, but it fails with gcc because the Python.h header is missing). 

Any ideas how I could fix this problem? It would be really helpful to hear which set-up (in particular, Cygwin vs. CMD, which compiler) worked to produce a Windows version. Or maybe it would even be possible to make a binary version available for download?

Thanks,
  Peter

**Comment by alexeyignatiev** [comment]
Hi Peter,

Our binary wheels are precompiled with the use of the Appveyor building system. The setup was prepared a few years ago by @rjungbeck. Currently, I simply continue using it, hence the builds for the latest versions of the toolkit. The latest version of PySAT has binary wheels listed [here](https://pypi.org/project/python-sat/#files).

You may want to try to install one of the most suitable ones of them directly. For that, you may need to install the right version of Python. Although I don't have access to Windows machines, my understanding is that the toolkit should be installable with no need for WSL. Perhaps, it should work with a standalone installation of Python for Windows. @rjungbeck may give you more hints if he has time.

Best,
Alexey

**Comment by rjungbeck** [comment]
The binary wheels that I made had been created in plain Windows without WSL.

My patches modified file.hpp to define NUNLOCKED (which should prevent the reference to getc_unlocked) if _MSC_VER is defined.

**Comment by alexeyignatiev** [comment]
Thank you for the reply, @rjungbeck. By any chance, could you build a wheel for PyPBLib for Python 3.10 on Windows? This would allow me to build vanilla Python 3.10 builds for PySAT on Windows.

**Comment by rjungbeck** [comment]
I have did an AppVeyor build for Python 3.10 for pypblib and pysat.  See the changes in my repositories. The only changes required were additional targets in appveyor.yaml, naming conventions for Python 3.10 downloads in instdep.py and a different source url for maplechrono and maplecm in solvers/prepare.py. I did only run the automated tests.

**Comment by alexeyignatiev** [comment]
Thank you, @rjungbeck. I made similar changes in the Appveyor-related files and managed to compile a wheel for Python 3.10.
