### ISSUE TITLE
Bad zip file or tar file

### ISSUE THREAD

**Issue by allrtaken** [pysathq/pysat#11]
Hi Alexey,

I tried installing PySAT via pip and compiling the source code, but errors are thrown while compiling maplesat, minicard and minisatgh. The type of errors is the same -- the downloaded tar or zip files could not be recognized. The dump for maplesat is as below:

> 
> preparing maplesat
>     downloading: solvers/maplesat.zip (675 bytes)... done
>     extracting solvers/maplesat.zip
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-zsQP_s/python-sat/setup.py", line 118, in <module>
>         install_requires=['pypblib>=0.0.3', 'six']
>       File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>         dist.run_commands()
>       File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
>         self.run_command('build')
>       File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/tmp/pip-build-zsQP_s/python-sat/setup.py", line 67, in run
>         prepare.do(to_install)
>       File "/tmp/pip-build-zsQP_s/python-sat/solvers/prepare.py", line 281, in do
>         extract_archive(sources[solver][-1], solver)
>       File "/tmp/pip-build-zsQP_s/python-sat/solvers/prepare.py", line 365, in extract_archive
>         myzip = zipfile.ZipFile(archive, 'r')
>       File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
>         self._RealGetContents()
>       File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
>         raise BadZipfile, "File is not a zip file"
>     zipfile.BadZipfile: File is not a zip file
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zsQP_s/python-sat/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-X4QLE2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-zsQP_s/python-sat/
> 

The dump for minisat is:

> preparing minicard
> downloading: solvers/minicard.tar.gz (675 bytes)... done
> extracting solvers/minicard.tar.gz
> Traceback (most recent call last):
>   File "setup.py", line 120, in <module>
>     install_requires=['pypblib>=0.0.3', 'six']
>   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
>     self.run_command('build')
>   File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "setup.py", line 69, in run
>     prepare.do(to_install)
>   File "/home/u1718431/Downloads/pysat/solvers/prepare.py", line 281, in do
>     extract_archive(sources[solver][-1], solver)
>   File "/home/u1718431/Downloads/pysat/solvers/prepare.py", line 352, in extract_archive
>     tfile = tarfile.open(archive, 'r:gz')
>   File "/usr/lib/python2.7/tarfile.py", line 1693, in open
>     return func(name, filemode, fileobj, **kwargs)
>   File "/usr/lib/python2.7/tarfile.py", line 1751, in gzopen
>     raise ReadError("not a gzip file")
> tarfile.ReadError: not a gzip file
> 

For now, I have removed the three solvers from the to_install list, and the installation completes. But help in getting the installation right would be appreciated.

Thanks!

**Comment by alexeyignatiev** [comment]
Hi Aditya,

That is a strange issue! Thanks for reporting!

The thing is that the installer first downloads the archives from the original sources before compiling them, e.g. MapleSAT is downloaded from [https://sites.google.com/a/gsd.uwaterloo.ca/maplesat/MapleCOMSPS_pure_LRB.zip](https://sites.google.com/a/gsd.uwaterloo.ca/maplesat/MapleCOMSPS_pure_LRB.zip), MiniCard from [https://github.com/liffiton/minicard/archive/v1.2.tar.gz](https://github.com/liffiton/minicard/archive/v1.2.tar.gz) while MiniSatGH from [https://github.com/niklasso/minisat/archive/master.zip](https://github.com/niklasso/minisat/archive/master.zip). And so I would guess this might have been caused by some connection issue. Could you try to install it again and see what happens?

```
pip install --upgrade --force-reinstall --no-cache-dir python-sat
```

**Comment by allrtaken** [comment]
Thanks Alexey! It seems it was indeed a network problem, probably because I am behind a firewall. I downloaded the last two files in your links manually, and put them in the solvers folder, and it worked (I'm building from source). I am unable to download from https://sites.google.com/a/gsd.uwaterloo.ca/maplesat/MapleCOMSPS_pure_LRB.zip because of firewall issues but it's clear what the problem is. Thanks again!
