### ISSUE TITLE
Multiple Cardinality Constraints

### ISSUE THREAD

**Issue by G-AshwinKumar** [pysathq/pysat#110]
Hello, I'm sure I'm probably missing something straightforward. 

Let's say I have 10 literals in total numbered 1-10 for which i want to add some constraints. For example I want to add two cardinality constraints, amo constraint for the first 5 literals and amok (k=4) for the literals 6-10. Now when I do something like 
```
cnf = CardEnc.atmost(lits=[1,2,3,4,5], bound= 1, encoding=1)
cnf_final.extend(cnf.clauses)
cnf = CardEnc.atmost(lits=[6,7,8,9,10], bound= 4, encoding=1)
cnf_final.extend(cnf.clauses)
```
This obviously doesn't seem right as the extra literal used for the first encoding will clash with the ones from the second encoding. How do I avoid such issues? I already know the maximum set of basic literal I need (in this case 1-10). Is there some parameter I could use to say all newly created literals should be above this set value which would be updated after each encoding? Basically, how do I go about creating a CNF where the clauses are built one after the other.

**Comment by alexeyignatiev** [comment]
Hey Ashwin,

You can surely do this using either `top_id` of `vpool` parameters. Something alone these lines:

```python
from pysat.card import *

# method 1 - with the use of top_id:

# manually indicate what the top variable is 
cnf1 = CardEnc.atmost(lits=range(1, 6), bound=1, encoding=EncType.seqcounter, top_id=10)
cnf2 = CardEnc.atmost(lits=range(6, 11), bound=2, encoding=EncType.seqcounter, top_id=cnf1.nv)

print(cnf1.clauses)
print(cnf2.clauses)

# method 2 - with the use of vpool
from pysat.formula import IDPool

# make a centralised pool for variable identifiers
pool = IDPool(start_from=11)

# use it whenever needed
cnf1 = CardEnc.atmost(lits=range(1, 6), bound=1, encoding=EncType.seqcounter, vpool=pool)
cnf2 = CardEnc.atmost(lits=range(6, 11), bound=2, encoding=EncType.seqcounter, vpool=pool)

print(cnf1.clauses)
print(cnf2.clauses)
```

**Comment by G-AshwinKumar** [comment]
Hey @alexeyignatiev 

The vpool method worked elegantly for my problem. Thanks for the quick and prompt response.

Thanks and Regards,
Ashwin
