### ISSUE TITLE
Cannot install on M1 mac

### ISSUE THREAD

**Issue by algebravic** [pysathq/pysat#115]
I'm trying to install python-sat on my M1 mac (supplied by my employer) running OSX 12.6.  It fails when compiling `pycard.cc`, specifically, in `bitwise.hh` line 11 it includes `cmath`.  I then get a bunch of errors "no template name 'numeric_limits'".  I'm using the xcode version 14.0.0 compiler.  Any suggestions?

**Comment by alexeyignatiev** [comment]
Honestly, I am not sure what to suggest. This looks like an issue with your SDK setup. My student has just compiled a binary wheel on his M1 laptop for Python 3.10. I uploaded it to PyPI. Can you try it?

**Comment by alexeyignatiev** [comment]
Compilation works just fine on my M1-powered laptop. So I assume the issue to be related to your SDK/paths setup. Closing. Feel free to reopen if you believe this is a general issue.
