### ISSUE TITLE
error in lsu

### ISSUE THREAD

**Issue by idotu** [pysathq/pysat#119]
I get an error when trying to solve with lsu:
File "/opt/homebrew/lib/python3.10/site-packages/pysat/examples/lsu.py", line 232, in solve
    self._assert_lt(self.cost)
  File "/opt/homebrew/lib/python3.10/site-packages/pysat/examples/lsu.py", line 313, in _assert_lt
    self.oracle.add_clause([-self.tot.rhs[cost-1]])
IndexError: list index out of range

**Comment by alexeyignatiev** [comment]
@idotu, how should I reproduce the issue and see if it is a bug?

**Comment by alexeyignatiev** [comment]
Also, as far as I understand, you may run `lsu.py` on a weighted instance while it [does not support](https://pysathq.github.io/docs/html/api/examples/lsu.html) weighted soft clauses. If that is your issue, you can use `rc2.py` instead.

**Comment by idotu** [comment]
Yes, that is the issue, I didn't see the warning note, and I was trying to solve a weighted instance.
Thanks!!!

**Comment by alexeyignatiev** [comment]
OK, good! Then this solves it.
