### ISSUE TITLE
Problem with RC2.compute <bound method RC2.compute of <pysat.examples.rc2.RC2 object at 0x7f53b354f7f0>>

### ISSUE THREAD

**Issue by PoplarTN** [pysathq/pysat#121]
Hi,

I'm quite new with SAT and I'm working on maxSAT problem, using RC2. Normally, the result of RC2.compute will return the set of variables with assigned values, but I got this result:

<bound method RC2.compute of <pysat.examples.rc2.RC2 object at 0x7f53b354f7f0>>

Could you please advise me what the problem come from? 
Thank you in advance!

**Comment by alexeyignatiev** [comment]
Well, in order to understand why you get this message, I will need to reproduce it. For that, a minimal example would be necessary.

**Comment by PoplarTN** [comment]
Thank you so much for your reply, this is my simple code

`
from pysat.formula import WCNF
from pysat.examples.rc2 import RC2

from pysat.card import *


k = 5
N = 10
M = 1000


cnf = WCNF()

#the number of variables N*2
sx = [[i+1, N+(i+1)] for i in range(N)]


# hard clauses"
for c in sx:
    cnf.append([-c[0], -c[1]])

# soft clauses
fx = []
for idx in range(M):
    fx.append((idx + 2 * N + 1))  
    cnf.append([-(idx + 2 * N + 1)], weight=1)

  
# here we call the solver.
with RC2(cnf) as rc2:
    print(rc2.compute)
    print(rc2.cost, "on", M, "examples")

`

**Comment by alexeyignatiev** [comment]
Good to know. I guess it was related to making an improper call of `compute()`. (In the example you shared there were no parentheses.) I am closing the issue.

**Comment by PoplarTN** [comment]
> Good to know. I guess it was related to making an improper call of `compute()`. (In the example you shared there were no parentheses.) I am closing the issue.

Yes, that's true! It's my stupid mistake
