### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required.

### ISSUE THREAD

**Issue by ajadam64** [pysathq/pysat#122]
Hi I get this error when trying to install python-sat via pip using pycharm on windows:

running build_ext
  building 'pycard' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

Please is there a work around, I don't want to install visual studio, how can I use mingw for this instead?

**Comment by alexeyignatiev** [comment]
I believe it is better to ask someone who actually has and uses Windows. @rjungbeck by any chance, could you please comment here?

**Comment by ajadam64** [comment]
Ok thanks

**Comment by rjungbeck** [comment]
I only ported the project to Visual Studio.
Normally PIP on Windows would use a WHL (already compiled) code if it is available.
I have modified my version of pysat (rjungbeck/pysat) and pypblib (rjungbeck/pypblib) to include Python 3.11 win64 as build target.

**Comment by alexeyignatiev** [comment]
Thanks, I will then include py3.11 too!
