### ISSUE TITLE
How to get the unsatisfiable soft clauses with RC2?

### ISSUE THREAD

**Issue by PoplarTN** [pysathq/pysat#123]
Dear all,

As far as I understand, the rc2.cost returns the numbers of the soft clauses that are not satisfied. I wonder is there any way to get (print out) these unsatisfiable soft clauses with RC2?

Thank you for your help!

**Comment by alexeyignatiev** [comment]
Hi @PoplarTN. The `cost` variable keeps the sum of weights of the falsified soft clauses. If all the weights are `1` then it equals the number of falsified soft clauses. As for printing the clauses, you should be able to easily do so by traversing the clauses and checking which of them are satisfied by the corresponding model returned from `compute()`.

**Comment by PoplarTN** [comment]
Hi @alexeyignatiev, 

After calling RC2(wcnf) and add some hard or soft clauses using add_clause(), how can we print out the hard clauses and soft clauses finally in RC2? As in case there are many variables and I understand that you managing the variables clashing when adding external variables have the same name with the internal ones that may be generated from the cardinality constraints.

**Comment by alexeyignatiev** [comment]
@PoplarTN, unfortunately, there is no way to print out the clauses sitting inside a SAT solver. This is the case after you ran RC2. Namely, RC2 modifies the working formula directly on the SAT solver's end and there is no access to what it stores afterwards. If you keep a copy of all the clauses you add somewhere on the side then you should be able to print them with ease.

**Comment by alexeyignatiev** [comment]
If you are talking about the check of which clauses are satisfied by the MaxSAT model then all the hard clauses are guaranteed to be satisfied. As for the soft clauses, those are easy to keep on the side for this final check.
