### ISSUE TITLE
Minisat22 crash

### ISSUE THREAD

**Issue by alexanderivrii** [pysathq/pysat#125]
When running via PyCharm on Windows, the following code
```
cnf = CNF(from_file='m22_bug.cnf')
s = Solver(name='m22', bootstrap_with=cnf)
result = s.solve()
```
produces an error 
```
Process finished with exit code -1073741819 (0xC0000005)
```

The CNF zipped file is attached:

[m22_bug.zip](https://github.com/pysathq/pysat/files/11241744/m22_bug.zip)

Other solvers seem to work fine on this problem.

**Comment by alexeyignatiev** [comment]
Thanks for reporting. Unfortunately, I don't have access to a Windows machine to reproduce this, and it seems to work just fine on macOS. The solver takes a bit of time deciding the formula's satisfiability but it does not gets killed.

**Comment by alexanderivrii** [comment]
Thanks for checking this. It could very well be some weird problem with my environment. You are welcome to close the issue.

**Comment by alexeyignatiev** [comment]
OK, thanks for confirming. I am closing it now.
