### ISSUE TITLE
Guidelines on patches

### ISSUE THREAD

**Issue by marino-mrc** [pysathq/pysat#134]
Hello,
I'm trying to add Glucose version 4.2.1 to PySat but I noticed that some patches are applied to solvers during the "build" step.
Do you have some guidelines on what should be changed in new solvers in order to make them compatible with the PySat build process? 
Thank you.
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

You can check what API is accessible for the other versions of Glucose in [`solvers/pysolvers.cc`](https://github.com/pysathq/pysat/blob/fe921db75c39746b3427e52363fb865082f65309/solvers/pysolvers.cc#L471). The patches are meant to deliver this API. Also, they make sure the main namespace of a solver is unique, in your case it should be `Glucose42`. Please let me know if you would like to get more information from me on this.

Best,
Alexey

**Comment by marino-mrc** [comment]
Thanks for your answer, Alexey.
I started some preliminary work, you can check it here: https://github.com/marino-mrc/pysat
but I have some questions:

1. Why the l_True, l_False and l_Undef have been renamed in glucose41?

From SolverTypes.h:
#define g41l_True  (Glucose41::lbool((uint8_t)0)) // gcc does not do constant propagation if these are real constants.
#define g41l_False (Glucose41::lbool((uint8_t)1))
#define g41l_Undef (Glucose41::lbool((uint8_t)2))

Is this needed?


2. At the moment I excluded the following function (it exists in Glucose41):
// Warm start mode:
inline void     Solver::setStartMode (bool warm) { warm_start = warm; cancelUntil(0); }

Is this really needed? And also, is this safe?


3. The following function:
bool Solver::addClauseWarm(vec<Lit>& ps)

is not used. It exists in patch files but is never called in pysolvers.cc. Is this needed? At the moment I excluded it in Glucose421

Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

Yes, the short answer is that all those things are needed. Point 1 is used in order not to mess up with all the constants appearing in all the MiniSat-based solvers, where these constants and namespaces are shared under the same name. Points 2 and 3 are needed for implementing warm starts and the addition of clauses during warm starts. The method `addClauseWarm()` is called from `addClause()` if the solver is in the warm start mode (see `core/Solver.h`) and it is defined in `core/Solver.cc`. I hope this helps.

Best,
Alexey

**Comment by alexeyignatiev** [comment]
Hi Marco,

Well, I can't reproduce the issue! Building works (`python setup.py build`) and running the test `tests/test_accum_stats.py`  in the build directory reports no problems on my laptop. :)

Best,
Alexey

**Comment by marino-mrc** [comment]
Hi Alexey,
I'm sorry but I have many questions:

1. Have you used my repo? please double check that in setup.py the "to_install" variable is defined as:

to_install = ['glucose421']

2. Are you using the libglucose421.a file? This is an archive file and I think there is some problem with the linker. Do I need to have a .so file instead?

3. How do you run the test? Please, share the exact command



Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

Here are my answers to your questions:

1. Not exactly, I use `to_install = ['glucose30' , 'glucose421']`.
2. Yes, PySAT makes use of static `.a` libraries.
3. This is what I do:
```bash
aign@orion:PYSATPATH$ python setup.py build
...
aign@orion:PYSATPATH$ cp -r tests build/lib.macosx-13-arm64-cpython-310/
aign@orion:PYSATPATH$ cd build/lib.macosx-13-arm64-cpython-310/
aign@orion:PYSATPATH/build/lib.macosx-13-arm64-cpython-310$ python tests/test_accum_stats.py
```

No issue is reported when I run the last command. Note that it does not mean there are no problems. It would be possible to test the functionality properly if there was a Python wrapper for Glucose42 in `pysat/solvers.py` but it is not yet there.

Best,
Alexey

**Comment by marino-mrc** [comment]
Hi Alexey,
I'm sorry but ... it doesn't work.
Which version of python are you using? Which OS?
Have you tried with my own fork from Guthub?

Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

Well, that is quite weird. I use MacOS Ventura 13.4 running on Apple M1 Pro. The version of Python is 3.10 and it is installed through Homebrew. And yes, I did pull [your fork](https://github.com/marino-mrc/pysat) of the repository. The latest commit pulled is titled _"Improved patch file for Glucose 4.2.1"_. What is your setup?

Best,
Alexey

**Comment by alexeyignatiev** [comment]
Having said that, Marco, it is better to use the Makefile setup as much as possible resembling those for the other solvers, including the compiler and the options used.

**Comment by marino-mrc** [comment]
Hi Alexey, finally it works! I did a commit a few minutes ago.
Please, note that some functions are still missing (addClauseWarm and so on... but it should be easy to fix)

Thank you for your help.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Thanks for the update, Marco. Congratulations!

**Comment by marino-mrc** [comment]
Hi Alexey, thanks again for your help.
I want to inform you that I did some other commits and now Glucose 4.2.1 is fully operational in my fork.
Some points:
- merge requests are welcome?
- if you will evaluate my code, feel free to raise any issue you found and I'll be glad to fix them

Thanks,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

This is an every good news, congratulations! Does it mean all the functionality of Glucose3 and Glucose4.1 is supported by the new solver? If yes then PRs are definitely more than welcome. And sure, if I find an issue, I will let you know.

Alexey

**Comment by marino-mrc** [comment]
Yes Alexey, everything should be supported now.

To be honest, I don't understand how the "test" folder works. If you don't call the method defined in *.py files, it will never be executed and this seems odd to me. Please, let me know if I missed something.
Btw, just created a PR.

Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

I left a comment for you there. As far as I can see, the current PR is not compilable on Windows. It may also not be compilable through WebAssembly. Please have a look.

As for tests, those aren't exhaustive and test some specific functionality of the toolkit.

Best,
Alexey

**Comment by marino-mrc** [comment]
Thank you Alexey.
Since the PR is done, I'm closing this issue.

Regards,
Marco
