### ISSUE TITLE
get_proof doesn't work in Glucose 4.2.1

### ISSUE THREAD

**Issue by marino-mrc** [pysathq/pysat#136]
Hello Alexey, 
the get_proof function doesn't work in Glucose 4.2.1.

I fixed this problem in my commit https://github.com/marino-mrc/pysat/commit/5141f0340473fa3cfe2f2af555be552c549c026a

Can I start another PR?

Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Sure, Marco, please go ahead.

**Comment by marino-mrc** [comment]
Hello Alexey,
thanks for accepting my PR.
I'm closing this issue now.

Regards,
Marco
