### ISSUE TITLE
Seemingly incorrect results when using pseudo-boolean constraints

### ISSUE THREAD

**Issue by benwh1** [pysathq/pysat#140]
I wrote the following script for testing:

```py
from pysat.formula import CNF
from pysat.solvers import Solver
from pysat.pb import PBEnc

formula = CNF()

pb = PBEnc.atleast(lits=[1,2,3,4,5,6,7,8], bound=6)
formula.extend(pb.clauses)

pb = PBEnc.atleast(lits=[1,2,3,4,-5,-6,-7,-8], bound=6)
formula.extend(pb.clauses)

solver = Solver(bootstrap_with=formula)
print("sat" if solver.solve() else "unsat")
```

So I have 8 variables x1, ..., x8 and I want at least 6 of x1, ..., x8 to be true and at least 6 of x1, x2, x3, x4, ¬x5, ¬x6, ¬x7, ¬x8 to be true. It seems obvious that this is satisfiable, just take x1, ..., x6 to be true and x7, x8 to be false.

But when I run the script, it prints `unsat`. I have tried manually adding in the `weights` parameter of `atleast`, using different encodings of the pseudo-boolean constraints, using different solvers, and everything I tried still results in `unsat`.

What am I doing wrong?

**Comment by benwh1** [comment]
Never mind... of course the first thing I try after posting an issue works. Happens every time.

The solution is to use `IDPool`.

```py
from pysat.formula import CNF, IDPool
from pysat.solvers import Solver
from pysat.pb import PBEnc

formula = CNF()
pool = IDPool(start_from=9)

pb = PBEnc.atleast(lits=[1,2,3,4,5,6,7,8], bound=6, vpool=pool)
formula.extend(pb.clauses)

pb = PBEnc.atleast(lits=[1,2,3,4,-5,-6,-7,-8], bound=6, vpool=pool)
formula.extend(pb.clauses)

solver = Solver(bootstrap_with=formula)
print("sat" if solver.solve() else "unsat")
```

**Comment by alexeyignatiev** [comment]
No worries, @benwh1. Thanks for checking!
