### ISSUE TITLE
`propagate()` on empty assumptions does not perform unit propagation?

### ISSUE THREAD

**Issue by aur3l14no** [pysathq/pysat#143]
``` python
cnf = CNF(from_clauses=[[1], [-1, 2], [-2, 3]])
solver = Solver(bootstrap_with=cnf)
print(solver.propagate([]))  # (True, []) instead of (True, [1, 2, 3])
```

Is it expected? And is there a way to perform unit propagation and simplify the formula?

Thanks a lot.

**Comment by alexeyignatiev** [comment]
Yes, @aur3l14no, this is to be expected. The method `propagate()` receives a list of assumptions and returns a list of literals (if any) propagated given the assumptions. Note that in your example no assumptions are provided, hence nothing is propagated.

I should also say that the unit clause you add in your example is treated as a literal simply added to the solver's trail followed by a series of propagation steps - this is done when adding the clauses. If you want to see what can be propagated from `[1]` in formula `[[-1, 2], [-2, 3]]`, you should do something like this:

```python
cnf = CNF(from_clauses=[[-1, 2], [-2, 3])
solver = Solver(bootstrap_with=cnf)
solver.propagate(assumptions=[1]) # (True, [1, 2, 3])
```

As I mentioned above, simplifications resulting from unit propagation are normally done by the solver when the clauses are being added. If you want to simplify `CNF` objects based on the outcomes of `propagate()` calls then you should be able to cook a procedure that would do that following the example above.

Finally, you may want to use the [`process`](https://pysathq.github.io/docs/html/api/process.html) module for preprocessing the formula.

I hope this helps.
