### ISSUE TITLE
No wheels for Python 3.11 on x86-64

### ISSUE THREAD

**Issue by embe-pw** [pysathq/pysat#144]
There is no prebuilt wheel file for `python-sat` for Python 3.11 on x86-64 on PyPI, so `pip install python-sat` builds it from source. This has two disadvantages:
1. It takes time.
2. It requires the C compiler to be available.

I think the cause is that the build for x86-64 is being done using a `manylinux2010` container, which is no longer being supported (see https://github.com/pypa/manylinux/issues/1281), so it does not contain current Python versions. I guess that upgrading to `manylinux2014` (note it is almost 10 years old!) would help with that.

**Comment by alexeyignatiev** [comment]
True, I should start compiling it for manylinux2014. Thanks for reporting.

**Comment by alexeyignatiev** [comment]
Now there should be binary wheels for the above configuration. Closing.
