### ISSUE TITLE
Unexpected MaxSat Solution from `RC2`

### ISSUE THREAD

**Issue by gdowdy3** [pysathq/pysat#145]
I modified the example found [here ](https://pysathq.github.io/docs/html/api/examples/rc2.html#examples.rc2.RC2.compute) as follows:

```python
from pysat.examples.rc2 import RC2
from pysat.formula import WCNF

rc2 = RC2(WCNF())  # passing an empty WCNF() formula
rc2.add_clause([-1, 2, 3])

rc2.add_clause([1], weight=-1)
rc2.add_clause([2], weight=1)
rc2.add_clause([3], weight=1)

model = rc2.compute()
print('Optimal Solution:', model)

rc2.delete()
```

The documentation of the `compute()` method says:

> This method can be used for computing one MaxSAT solution, i.e. for computing an assignment satisfying all hard clauses of the input formula and maximizing the sum of weights of satisfied soft clauses. 

Accordingly, I would expect the modified code above to find the solution of `[-1, 2, 3]`, which corresponds to a sum of satisfied weights of `2`.

However, when I actually run the code, it produces the following output:
```
Optimal Solution: [1, 2, 3]
```

This solution has a sum of satisfied weights of `1`.  Since `1 < 2`, I would say that this is not, in fact, "an assignment satisfying all hard clauses of the input formula and *maximizing the sum of weights of satisfied soft clauses.*"

Is this a bug, or am I misunderstanding something?

**Comment by gdowdy3** [comment]
FYI, @gozwei

**Comment by alexeyignatiev** [comment]
@gdowdy3, PySAT does support negative weights in a WCNF formula when it parses the formula from a file and so does RC2. But when you cook up clauses on the fly, you don't handle negative weights manually (nor does PySAT at a solver level). I agree this isn't ideal and an easier-to-use solution would be nice to have.
