### ISSUE TITLE
Unused variables do not occur in model

### ISSUE THREAD

**Issue by LemarAb** [pysathq/pysat#149]
Since it might me a problem you guys have already dealt with: 

I set variables from `vpool` and also ensured that, particularly for the last 4 variables, there is a mapping in `vpool` by using `vpool.obj(x)`. However, once I print the `model`, the last four variables are not even shown in the list. Is there some kind of intention behind PySAT that might lead to this output? For what it is worth, the variables are mapped but never used in the built `CNF`, so do you guys remove them from `model` in that case? From my understanding, even if we dont use a variable and it therefore is a 'dont-care' argument, it should appear in the `model`.

**Comment by alexeyignatiev** [comment]
@LemarAb, SAT solvers assign all the variables _appearing_ in an input CNF formula but they ignore variables that aren't present. Also, if you have a gap in variable ids then the gap's variables should surely be assigned to some values because the solvers aren't clever enough to treat the gaps properly. But if the missing variables are the last ones, the solvers will fail to give any values to them - from their perspective, these variables do not exist at all.

**Comment by alexeyignatiev** [comment]
While we could add a somewhat clever model post-processor and give some default values to non-existing variables, not every user needs this while this certainly would slow things down. This is why no such post-processing is included. I think the easiest way for you would be to add it on your end as it's pretty simple.

**Comment by LemarAb** [comment]
thank you so much for your answer! If you allow another question: If we do use variables that end up being dont-care variables (i.e. x or -x), does PySAT set these to false by default?

**Comment by alexeyignatiev** [comment]
No, it will not necessarily set it to `False`. This depends on the heuristics used by a SAT solver of your choice (for instance, default variable polarity and/or the use of static heuristics for phase selection as well as the use of phase saving).

**Comment by LemarAb** [comment]
For my instance, I would like to solve my boolean formula with PySAT and set dont-cares to `False`, so is there a possibility to do so?

**Comment by alexeyignatiev** [comment]
PySAT does not have default polarities but SAT solvers used by it do have this.

**Comment by alexeyignatiev** [comment]
Regarding opting for `False` as the default polarity, you can use the `set_phases()` functionality to specify which polarities you would like to get.

**Comment by LemarAb** [comment]
ok, do you know which Solver is used when calling the standard `Solver` as solver? If so, does that solver have default polarity set to `false` and if not, which solver could I use instead?

**Comment by alexeyignatiev** [comment]
The default solver is [MiniSat 2.2](https://pysathq.github.io/docs/html/api/solvers.html#pysat.solvers.Solver). And, yes, this solver does set variables to `False` by default unless the phase is reset by phase saving.

**Comment by LemarAb** [comment]
thank you so much!

**Comment by alexeyignatiev** [comment]
No worries!
