### ISSUE TITLE
Solver get_core() returns None even if UNSAT

### ISSUE THREAD

**Issue by kkew3** [pysathq/pysat#15]
According to [doc](https://pysathq.github.io/docs/html/api/solvers.html#pysat.solvers.Solver.get_core), `get_core()` returns `None` only if previous call is not `UNSAT`. However, I found a case that violates the instruction.

How  to reproduce:

```python
import json
from pysat.solvers import Solver
with open('clauses.txt') as infile:
    clauses = json.load(infile)
with Solver(bootstrap_with=clauses) as s:
    print(s.solve())  # --> False
    print(s.get_core())  # --> None
```

[clauses.txt](https://github.com/pysathq/pysat/files/3353171/clauses.txt)

Thanks

**Comment by alexeyignatiev** [comment]
Well, as the documentation explains, a core is extracted as a subset of the given list of assumptions, following the standard MiniSat-like setup for incremental SAT solving. Since you don't specify any assumptions, there is no core. I hope this helps.

**Comment by kkew3** [comment]
Oh I see. Thank you so much. I'm closing this, but would it be better should it be added to doc of `get_core()`?
