### ISSUE TITLE
Extracting learned clauses (during a search)

### ISSUE THREAD

**Issue by MushroomHunting** [pysathq/pysat#150]
Hi there,

Before I start, wanted to say thanks for the amazing library!

Pretty easy question that I couldn't find an obvious answer to. Is it possible to extract/query the learned conflict clauses from the underlying solvers during their runtime? If there is and if it's documented could you please direct me to where I can find more details

cheers!

**Comment by alexeyignatiev** [comment]
Having said that, I am not sure what you mean by extracting them during search. The call sto `get_proof()` can be made between SAT calls.

**Comment by MushroomHunting** [comment]
Hi @alexeyignatiev , Thanks for the reply and so sorry for the long delay in replying. I was curious to visualise the problem structure as a function of time and learned clauses (much like in https://www.labri.fr/perso/lsimon/downloads/papers/jair19.pdf). But this would not be possible if a problem is unsat or just awfully difficult to solve. It seems that get_proof() would only give the proof _after_ the search has terminated. Do you know if any of the current solvers allow such a access during the search - i guess this would amount to accessing the clause database. Would be ok if you could suggest external (from pysat) libraries that allow this capability.

As a follow up question to your reply; I'm not sure I fully understand the DRUP format. Am I interpreting it correctly if one were to take the non-deleted ('d .... 0') lines of the proof and interpret them as the clauses learned, in order, during the search? If not how would I interpret the proof in terms of learned clauses. Apologies in advance if these are silly questions! 

cheers,
Anthony

**Comment by alexeyignatiev** [comment]
Hi @MushroomHunting,

I am afraid that off the top of my head I can't name the tools that would give you access to their internal learnt clause database. As for the DRUP proofs, those need to be read in order from the beginning to the end of the file/string. Each line corresponds to the point when a new clause is inferred/added to the formula or deleted (if the line if prepended with a `d`). Note that the same clause may be added and then deleted during the refutation process (furthermore, this may happen multiple times if we are particularly unlucky).

Best,
Alexey
