### ISSUE TITLE
Docs: `BeyondNP` link is broken

### ISSUE THREAD

**Issue by dulanov** [pysathq/pysat#151]
Feeling that servers are turned off, since the domain is still relevant.

Solution: in such cases switch from direct links to web archive - [BeyondNP](https://web.archive.org/web/http://beyondnp.org/).

**Comment by alexeyignatiev** [comment]
Thank for reporting. I will fix this.

**Comment by alexeyignatiev** [comment]
This is fixed now. Again, thanks for reporting!
