### ISSUE TITLE
Obtaining cores with solve_limited

### ISSUE THREAD

**Issue by ozan-cb** [pysathq/pysat#153]
I'm a bit confused about how `solve_limited` works. This is the signature of `solve_limited` in `Cadical153`:

```
def solve_limited(self, assumptions=[], expect_interrupt=False):
```
indicating that we can pass assumptions to the call, and can obtain a core if the given assumptions are infeasible.

However, if I do a call like

```python
...
solver.conf_budget(1000000)
status = solver.solve_limited(assumptions)
if status is not None and not status:
    core = solver.get_core()
    ...
...
```
The call to `solver.get_core()` fails with

```
  File "/lib64/python3.8/site-packages/pysat/solvers.py", line 1852, in get_core
    return pysolvers.cadical153_core(self.cadical, self.prev_assumps)
AttributeError: 'Cadical153' object has no attribute 'prev_assumps'
```
which makes sense when I look at the source code, since `self.prev_assumps` is [only set ](https://github.com/pysathq/pysat/blob/master/pysat/solvers.py#L1763) in calls to `solve` but not in calls to `solve_limited`. Is this a bug, or am I misunderstanding how assumptions are used in combination with `solve_limited`? What would be the way to obtain a core when a `solve_limited` call does not hit the given conflict limit?

**Comment by alexeyignatiev** [comment]
This is definitely a bug, @ozan-cb. Thanks for reporting. Hopefully, [f8ea0b8](https://github.com/pysathq/pysat/commit/f8ea0b81641ee936b1663253601ad1831dfecf92) and the version 0.1.8.dev13 should fix this. Let me know otherwise.

**Comment by ozan-cb** [comment]
0.1.8.dev13 fixes the issue. Thanks a lot for the quick fix @alexeyignatiev!
