### ISSUE TITLE
How to use a custom SAT solver within PySAT?

### ISSUE THREAD

**Issue by piyush-J** [pysathq/pysat#154]
Thank you for this amazing library! 

I have a quick question - Is there a way to use my own solver (built on top of MapleSAT) within PySAT? If yes, how should I do so?

**Comment by alexeyignatiev** [comment]
Well, it is not trivial to include an arbitrary solver. You will have to integrate it in the library to compile (see what is done in `solvers/pysolvers.cc` and then expose the Python interface.
