### ISSUE TITLE
Incorrect sign convention in CryptoMinisat core

### ISSUE THREAD

**Issue by noajshu** [pysathq/pysat#155]
Reproducing example:
```python
!pip install --quiet --upgrade python-sat[cryptosat]

import pysat.solvers

with pysat.solvers.Minisat22(bootstrap_with=[[-1, 2], [-2, 3]]) as m:
  print(m.solve(assumptions=[1, -3]))
  print(m.get_core())

with pysat.solvers.CryptoMinisat(bootstrap_with=[[-1, 2], [-2, 3]]) as m:
  print(m.solve(assumptions=[1, -3]))
  print(m.get_core())
```
Output:
```
False
[-3, 1]
False
[-1, 3]
```
Expected the cores should match.

Pysat's wrapper should probably be doing `*= -1` on each entry of the core here:
https://github.com/pysathq/pysat/blob/bcc67d21232b07695aa210234042d9e5350b42fa/pysat/solvers.py#L6691

I think it is related to this line of pycryptosat:
https://github.com/msoos/cryptominisat/blob/2a7b9021f0b355c96da89b734b7f452debc5c6ef/python/src/pycryptosat.cpp#L771

**Comment by alexeyignatiev** [comment]
Thanks, @noajshu. I think you are right. I will fix this shortly.

**Comment by alexeyignatiev** [comment]
Closing as version `0.1.8.dev15` fixes this.
