### ISSUE TITLE
Method to get list of clauses after propagation?

### ISSUE THREAD

**Issue by gdowdy3** [pysathq/pysat#159]
This may be an ignorant question, but is there a way to get the list of clauses known to the solver after calling the `propagate` method?  For example, I'd like to do something like this:

```python
with Glucose3(bootstrap_with=original_cnf_clauses) as solver:

        # Propagate any unit clauses in the original CNF clauses
        solver.propagate()

        # Get the resulting set of clauses
        post_propagation_clauses = solver.get_clauses()
```

**Comment by gdowdy3** [comment]
What I'm asking for here is closely related to the `nof_clauses()` method (as described here: https://pysathq.github.io/docs/html/api/solvers.html?highlight=unit%20propagation#pysat.solvers.Solver.nof_clauses), but I'm interested in the clauses themselves, not just their count.

**Comment by alexeyignatiev** [comment]
It's not an ignorant question and the answer is it is currently impossible. Extracting clauses is not implemented for any of the solvers as it feels difficult to justify the effort to be honest.
