### ISSUE TITLE
CNF.nv is wrong

### ISSUE THREAD

**Issue by kkew3** [pysathq/pysat#16]
`self.nv` of `pysat.formula.CNF`, according to [doc](https://pysathq.github.io/docs/html/api/formula.html#pysat.formula.CNFPlus.append), should be the number of variables. It can be verified that:

```python
from pysat.formula import CNF
assert CNF(from_clauses=[[1],[2]]).nv == 2
```

However, an error occurs here:

```python
from pysat.card import CardEnc
assert CardEnc.equals([1,2],2).nv == 2  # failed
```

See screenshot:

![image](https://user-images.githubusercontent.com/13264071/60572106-73d5c700-9da7-11e9-9de5-60b1078a010b.png)

Thanks!

**Comment by alexeyignatiev** [comment]
Hi @kkew3, thanks for reporting! Although this is a minor issue, I will try to fix it soon.

**Comment by alexeyignatiev** [comment]
This is fixed now. I am closing the issue. If something is still wrong, feel free to reopen. And thanks again for posting the issue.

**Comment by kkew3** [comment]
BTW, though could be a taste of coding issue, but it might be faster to write

```python
top_id = max(map(abs, lits))
```

rather than

```python
top_id = max(map(lambda x: abs(x), lits))
```

in the latest commit. Thanks for fixing the `nv` problem.
