### ISSUE TITLE
Retrieve partial solution

### ISSUE THREAD

**Issue by TraianDobrin** [pysathq/pysat#161]
Hello!

I was wondering if there was a way of retrieving a solution from a MaxSAT solver like RC2 after a certain amount of time, but before it finishes computing

Thank you.

**Comment by alexeyignatiev** [comment]
Hi @TraianDobrin,

In general, MaxSAT solvers like RC2 refine the lower bound on the solution cost, which means the first solution satisfying the hard clauses you get is the optimal one - there are no preliminary (non-optimal) solutions.
Some of the heuristics though (like *unsatisfiable core exhaustion*, see option `-x`) often result in satisfiable outcomes in between the majority of unsatisfiable ones. This is when you might want to extract a non-optimal solution. If you do so, notice that these solutions are not meant to approximate the optimal one, i.e. they not be interesting to you if you want to approximate the cost function.

Best,
Alexey
