### ISSUE TITLE
(p ↔ p) simplifies to p

### ISSUE THREAD

**Issue by ningit** [pysathq/pysat#163]
The following snippet prints `Atom(2)` while  *p* ↔ *p* is not equivalent to *p* (but to true).

```python
from pysat.formula import Atom, Equals

p = Atom(2)
f = Equals(p, p)

print(repr(f.simplified()))
```

The problem seems to be in the conditional of line [2319](https://github.com/pysathq/pysat/blob/master/pysat/formula.py#L2319-L2320) of `Equals.simplified` in `formula.py`. This simplification rule is not valid.

**Comment by alexeyignatiev** [comment]
Thanks for reporting, @ningit. This looks like a bug, which requires fixing.

**Comment by ningit** [comment]
I suggest adding
```python
if not (t_present or f_present):
    return PYSAT_TRUE
```
inside the conditional. Currently, it assumes there is a *true* or *false* in addition to that argument, but this may not be the case.

**Comment by alexeyignatiev** [comment]
It does not seem to solve this particular issue. Also, I found other similar issues in the simplification of other connectives.

**Comment by ningit** [comment]
Thanks, @alexeyignatiev, for your reply.

At least, it solves my example. Now I obtain `Atom(True)`.

**Comment by alexeyignatiev** [comment]
No worries, @ningit. I will try to fix this and other issues as soon as I can.

By the way, you may well be correct that checking `if not (t_present or f_present)` may suffice. As there is no `t_present` or `f_present` then none of the sub-terms got simplified by the above loop, which means the only way to get a single remaining sub-term is to remove duplicates, i.e. this happens only if we have a tautological equality.

**Comment by alexeyignatiev** [comment]
Hey @ningit, this and a few other similar issues should be fixed in the latest version. I am closing this now. Feel free to reopen if the issue remains!
