### ISSUE TITLE
the s->prop_check(a, p, save_phase) in solvers/pysolvers.cc

### ISSUE THREAD

**Issue by zhangran7** [pysathq/pysat#174]
Can anyone tell me, where is the definition of function prop_check(a, p, save_phase)? 
thx!!

**Comment by alexeyignatiev** [comment]
Various solvers have it defined in different files. If you are interested in MiniSat-based solvers, those define it in `core/Solver.cc`.

**Comment by zhangran7** [comment]
> Various solvers have it defined in different files. If you are interested in MiniSat-based solvers, those define it in `core/Solver.cc`.

But i can not find any prop_check( ) in core/Solver.cc in minisat22, please give me more hints，thx..

**Comment by alexeyignatiev** [comment]
The method is defined in lines 438-486 of the file `core/Solver.cc`. The definition is added by the patch `minisat22.patch`.
