### ISSUE TITLE
package install error

### ISSUE THREAD

**Issue by EricWong1992** [pysathq/pysat#18]
compiling maplecm
  c++ -std=c++11 -fPIC -Wall -Wno-deprecated -fno-strict-aliasing -I.. -O3 -DNDEBUG -c core/Solver.cc -o core/Solver.o
  core/Solver.cc: In member function ‘bool MapleCM::Solver::simplifyLearnt_core()’:
  core/Solver.cc:549:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                       if (nblevels < c.lbd()){
                                    ^
  core/Solver.cc: In member function ‘bool MapleCM::Solver::simplifyLearnt_tier2()’:
  core/Solver.cc:628:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                       if (nblevels < c.lbd()){
                                    ^
  core/Solver.cc: In member function ‘bool MapleCM::Solver::simplifyUsedOriginalClauses()’:
  core/Solver.cc:734:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                           if (nblevels < c.lbd()){
                                        ^
  core/Solver.cc:687:12: warning: variable ‘avg’ set but not used [-Wunused-but-set-variable]
       double avg;
              ^
  core/Solver.cc: In member function ‘bool MapleCM::Solver::simplifyOriginalClauses()’:
  core/Solver.cc:850:12: warning: variable ‘avg’ set but not used [-Wunused-but-set-variable]
       double avg;
              ^
  c++ -std=c++11 -fPIC -Wall -Wno-deprecated -fno-strict-aliasing -I.. -O3 -DNDEBUG -c utils/Options.cc -o utils/Options.o
  c++ -std=c++11 -fPIC -Wall -Wno-deprecated -fno-strict-aliasing -I.. -O3 -DNDEBUG -c utils/System.cc -o utils/System.o
  preparing maplesat
  error: <urlopen error [Errno 110] Connection timed out>
  ----------------------------------------
  ERROR: Failed building wheel for python-sat
  Running setup.py clean for python-sat
  Building wheel for pypblib (setup.py) ... done
  Created wheel for pypblib: filename=pypblib-0.0.4-cp35-cp35m-linux_x86_64.whl size=2396599 sha256=f6efe9002856681f8a69e9a1bc8fb7cd5560050d3c69fd4bc133b8e5f24b0c3e
  Stored in directory: /tmp/pip-ephem-wheel-cache-5248gqqs/wheels/e2/92/98/d86282d693afed7b944be1ec76ff605de9ff93d1a51634e624
  Building wheel for parsimonious (setup.py) ... done
  Created wheel for parsimonious: filename=parsimonious-0.8.1-cp35-none-any.whl size=50875 sha256=ad7d3374b6325b8bf59fb74cef97b8733bb1f76d4c6597264e85d9bb81924e95
  Stored in directory: /tmp/pip-ephem-wheel-cache-5248gqqs/wheels/b7/8d/e7/a0e74217da5caeb3c1c7689639b6d28ddbf9985b840bc96a9a
  Building wheel for attr (setup.py) ... done
  Created wheel for attr: filename=attr-0.3.1-cp35-none-any.whl size=3588 sha256=77ff4177f5f6c71f6391ab8492369a39d606dfda7ecc80707a5107adfc9f72d9
  Stored in directory: /tmp/pip-ephem-wheel-cache-5248gqqs/wheels/f0/96/9b/1f8892a707d17095b5a6eab0275da9d39e68e03a26aee2e726
Successfully built pypblib parsimonious attr
Failed to build python-sat
Installing collected packages: parsimonious, bidict, funcy, toposort, attr, click, py-aiger, pypblib, python-sat
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/parsimonious'
Consider using the `--user` option or check the permissions.

I have tried many times. Every time it stuck on "preparing maplesat".

**Comment by alexeyignatiev** [comment]
Hi @EricWong1992, thanks for reporting!

As far as I can see, it also complains about some permissions being denied. In either case, can you check if you are able to reach [this archive](https://sites.google.com/a/gsd.uwaterloo.ca/maplesat/MapleCOMSPS_pure_LRB.zip) of MapleSAT? This is what the installer tries to do. For some reason, it fails to download it on your machine. It would be great to understand why. I have checked it right now and the file is still perfectly reachable from here.

Also, are you using any proxy that Python may not know of? If you are, this may be the culprit. But this has to be checked.

**Comment by EricWong1992** [comment]
I have used the "sudo" command, I don't know why there are some permissions denied. I'm not very familiar with Linux.
I'm not able to reach the archive of MapleSAT because I'm in China. You know the reason.😂 I can't reach to google.com.
Are there any other ways I can get the archive?

**Comment by EricWong1992** [comment]
> Hi @EricWong1992, thanks for reporting!
> 
> As far as I can see, it also complains about some permissions being denied. In either case, can you check if you are able to reach [this archive](https://sites.google.com/a/gsd.uwaterloo.ca/maplesat/MapleCOMSPS_pure_LRB.zip) of MapleSAT? This is what the installer tries to do. For some reason, it fails to download it on your machine. It would be great to understand why. I have checked it right now and the file is still perfectly reachable from here.
> 
> Also, are you using any proxy that Python may not know of? If you are, this may be the culprit. But this has to be checked.

Thank you for your reply.
I have used the "sudo" command, I don't know why there are some permissions denied. I'm not very familiar with Linux.
I'm not able to reach the archive of MapleSAT because I'm in China. You know the reason.joy I can't reach google.com.
Are there any other ways I can get the archive?

**Comment by alexeyignatiev** [comment]
I see... :) Well, you can try to get the file using some *alternative ways*. Do you know what I mean? :)

After you have it downloaded, you can try to install the library manually:
```
$ git clone https://github.com/pysathq/pysat.git
$ mv MapleCOMSPS_pure_LRB.zip pysat/solvers/maplesat.zip
$ cd pysat
$ python setup.py build
```

If the last command does not fail, i.e. if everything compiles with no errors, you can then do:

```
$ [sudo] pip install -e .
```

This should do the trick.

**Comment by EricWong1992** [comment]
@alexeyignatiev It worked! Thank you very much. LOl!

**Comment by alexeyignatiev** [comment]
Great to know that it worked! :)
