### ISSUE TITLE
Pseudo-Boolean encodings for atleast and atmost

### ISSUE THREAD

**Issue by anirjoshi** [pysathq/pysat#182]
Hello,

 I installed pblib using the command `pip install pypblib` mentioned on this webpage [PySAT](https://pysathq.github.io/docs/html/api/pb.html). It seems like the encoding type native is not working with atleast and atmost constraints. The following code outputs an empty list of clauses. Is there any way to fix this?
 Also, an empty clause is `False` and an empty list of clauses is `True` according to the convention followed in PBLib, correct?  
```
from pysat.pb import *
s = PBEnc.atmost([1,2], weights=[2,2],bound=3, encoding=6)
print(s.clauses)
```

When I change the encoding from 6 to 5 or 4, it seems to work fine. Is there any way to resolve this issue?

Best

**Comment by alexeyignatiev** [comment]
Hi @anirjoshi,

This is because native representation is not clausal. If you do `print(s.atmosts)`, you will see the native representation. Note that the only way to deal with them at this point is with `Cadical195`.

Best,
Alexey

**Comment by alexeyignatiev** [comment]
Something along these lines:

```python
>>> from pysat.pb import *
>>> s = PBEnc.atmost([1,2], weights=[2,2],bound=3, encoding=6)
>>>
>>> from pysat.solvers import Cadical195
>>> with Cadical195(bootstrap_with=s, native_card=True) as solver:
...     for model in solver.enum_models():
...         print(model)
...
[-1, 2]
[1, -2]
[-1, -2]
```

**Comment by anirjoshi** [comment]
Great! Thank you!
