### ISSUE TITLE
ModuleNotFoundError: No module named 'pysat'

### ISSUE THREAD

**Issue by adikp98** [pysathq/pysat#184]
I am using Pycharm in Windows.

I have installed python-sat in anaconda prompt. But when I imported "from pysat.solvers import Minisat22" in Pycharm, I am getting error as:
    from pysat.solvers import Minisat22
ModuleNotFoundError: No module named 'pysat'

(cirSAT_GNN) C:\Users\adity>pip install python-sat
Collecting python-sat
  Using cached python_sat-1.8.dev13-cp310-cp310-win_amd64.whl.metadata (1.6 kB)
Requirement already satisfied: six in c:\users\adity\anaconda3\envs\cirsat_gnn\lib\site-packages (from python-sat) (1.17.0)
Using cached python_sat-1.8.dev13-cp310-cp310-win_amd64.whl (1.3 MB)
Installing collected packages: python-sat
Successfully installed python-sat-1.8.dev13

(cirSAT_GNN) C:\Users\adity>python --version
Python 3.10.15

(cirSAT_GNN) C:\Users\adity>

**Comment by adikp98** [comment]
I will close this for now, as I see some strange behavior at my end. I need to  confirm if the issue is because of my installation or else something else.

**Comment by alexeyignatiev** [comment]
Thanks, this should clearly be an installation issue.
