### ISSUE TITLE
Problem with py-aiger + python 2.7

### ISSUE THREAD

**Issue by allrtaken** [pysathq/pysat#19]
Hi Alexey,

I freshly pip-installed the latest version of pysat, and there appears to be some problem with py-aiger. I get the following error when I import pysat in my script:

Traceback (most recent call last):
  File "countPM.py", line 2, in <module>
    from pysat.formula import CNF, IDPool
  File "/usr/local/lib/python2.7/dist-packages/pysat/formula.py", line 209, in <module>
    import aiger
  File "/usr/local/lib/python2.7/dist-packages/aiger/__init__.py", line 2, in <module>
    from aiger.aig import AIG
  File "/usr/local/lib/python2.7/dist-packages/aiger/aig.py", line 12
    return f"{name}##time_{time}"
                                ^
SyntaxError: invalid syntax

I presume this has to do with using python2.7 and py-aiger. I am running Ubuntu 16.04 and py-aiger is the version automatically fetched when installing pysat. Thanks!

**Comment by alexeyignatiev** [comment]
Hi Aditya,

First of all, thanks for reporting! I did not notice this myself as I use Python 3.

Yes, it must be related with the version of Python you are using. Give me a moment. I will add a check on whether py-aiger is importable so that no such error is thrown on Python 2.

Best,
Alexey

**Comment by alexeyignatiev** [comment]
Hi Aditya,

Please, update the library (``pip install -U --no-cache-dir python-sat`` -- this should install version 0.1.4.dev18) and check if it is working now. Note that py-aiger will not work. But you can at least use PySAT. If that is fine, please, close the issue.

Alexey

**Comment by allrtaken** [comment]
It's working now -- thanks a lot!
