### ISSUE TITLE
Depend on py-aiger-cnf instead of py-aiger

### ISSUE THREAD

**Issue by mvcisback** [pysathq/pysat#21]
Hello,

I see that `pysat` now supports using `py-aiger` inputs (very cool!)

It looks like it's only being used as input and then being converted to CNF. If so, it might be better to depend on [py-aiger-cnf](https://github.com/mvcisback/py-aiger-cnf). 

- This package tracks `py-aiger` development so it should isolate you API changes.
-  `py-aiger-cnf` also woks some of the ecosystem libraries such as the bitvector extensions (`py-aiger-bv`), (really anything that exports an `aig` attribute).

I would be happy to help with the integration.

**Comment by alexeyignatiev** [comment]
Hi @mvcisback,

Thanks for the suggestion!

Do you mean replacing what is currently implemented in PySAT with the functionality of ``py-aiger-cnf``? As you correctly note, at this point our use of ``py-aiger`` is simplistic - we just encode an ``aiger`` object to CNF. However, the implementation makes use of internal data structures like CNF and IDPool, which is important. I am not sure it would be simpler to implement this through ``py-aiger-cnf``. Please, let me know if I am wrong.

Also, pull requests are more than welcome. :)

**Comment by mvcisback** [comment]
Ah, I think I should elaborate. The `py-aiger-cnf` output is fairly simplistic. Its definition is

```python
class CNF(NamedTuple):
    clauses: List[Tuple[int]]
    symbol_table: Mapping[str, int]
    max_var: int
```

I was proposing rewriting the usage of py-aiger to essentially:

```python
cnf = aig2cnf(aig)
for clause in cnf.clauses:
    # -- Add clauses and symbols to IDPool/internal CNF structure.
```

I'm happy to help with a PR, but I must confess I haven't looked at the internals of `pysat`.

**Comment by alexeyignatiev** [comment]
Hi @mvcisback, thanks for the reply. I checked the source code of ``aig2cnf()``. One comment is that you should not add the last (unit) clause forcing the output to be true (see line 53) unless you want to make only one specific SAT call.

What is more important is that we can have ranges of already occupied variable identifiers in ``IDPool``. And so if we use ``aig2cnf()`` in such a situation, we would have to go over all variables of the encoded formula and remap them to fresh identifiers if there is an intersection with the occupied identifiers. This may lead to unnecessary computation. Let me think if there is an easy way to go.

**Comment by mvcisback** [comment]
**Re line 53**: Good point! I had designed it for another library that wraps py-sat (https://github.com/mvcisback/py-aiger-sat), but only ever used it with a single SAT call.

**Re IDPool**: I think that could be an easy change on my end. Namely, instead of using the fresh function on [line 25](https://github.com/mvcisback/py-aiger-cnf/blob/3c31c84b3d22052538df5254f0625ec85ad2133f/aiger_cnf/cnf.py#L25), I could optionally let another function which closes over an `IDPool` handle creating literals. If that function is not specified, it'd do what it does now.

I wouldn't be able to use a `defaultdict` anymore (since the ID depends on the gate), but other than that it's a simple change on my end.

**Comment by mvcisback** [comment]
@alexeyignatiev So I've gone ahead implemented those changes and published under `v1.1.0`.

Again, the main benefit of this change would be to isolate yourself from changes to `py-aiger`.

**Comment by mvcisback** [comment]
@alexeyignatiev Good to hear that it sounds doable :). I'll have some time this weekend to maybe take a stab at a PR. I imagine once I actually start, some of these issues will naturally iron themselves out.

- **Re variable introduction:** I think the confusion is coming from my perhaps overly clever use of `defaultdict`. I subclass `defaultdict` on [line 11](https://github.com/mvcisback/py-aiger-cnf/blob/master/aiger_cnf/cnf.py#L11). This makes it so that the fresh function is called when a key is accessed that has not already be used. If it's not missing, it looks up the previously used value. I preferred it this way, that way I didn't accidentally forget to check if the variable already existed.

- **Re Boolean variables**: I'm not 100% sure what you mean by encoding here. I perhaps naively take the inputs to be what is returned via the aig's input attribute, e.g., `circ.inputs`. They aren't really interpreted (at least in `py-aiger-cnf`) outside of being hashable. The assumption regarding existing variables is that they are already present in the passed in `symbol_table` (default `None`) or they are handled by the `fresh` function.

- **Re type of input circ**: Currently my only assumption on circ is that it exposes the `.aig` attribute. Most of the objects in the `py-aiger-*` libraries I have written that represent `AIG`s have this attribute (including the `AIG` type). I would be happy to also support `string` and `file` inputs.

**Comment by alexeyignatiev** [comment]
@mvcisback, thanks for the reply. Please, keep in mind these points when working on the PR. Also, let me know if you need help. I might be able to find some time to look into this.

**Comment by mvcisback** [comment]
@alexeyignatiev I have created a draft PR. It uses my recent changes in `py-aiger-cnf` to isolate `pysat` from potential changes to `py-aiger` and factor out the generally useful AIG Tseitin transformation.

One question that I still don't understand is how to best force the output to be true. I understand that if this is an intermediate AIG just encoding variables, you don't want this, but it does seem like a fairly common usecase when working with AIGs. E.g. Create a BoolExpr that represents a predicate and you want to see if there exists inputs that satisfy this predicate.

**Comment by alexeyignatiev** [comment]
@mvcisback, thanks! Let me check the PR.

Regarding your question, you don't need to do anything with the output. It is up to a user to decide what exactly to do with the circuit. As long as there is access to the output variables, the user can force them to be true or false or to use them in a complex formula. The latter option enables one to make all sorts of SAT oracle calls and this is what we need to target. So, we really need to make sure there is explicit access to the input and output variables. I will need to check that in the PR.

**Comment by alexeyignatiev** [comment]
@mvcisback, it would be great if you could fix the following issues:

- the result `CNF` object should have a non-zero number of variables (see `.nv` variable)
- the current version maps integers to strings of the form `Input(name='var')`; it would make sense to map them to `'var'` instead.

Except for these issues, the implementation works fine. Thanks!

**Comment by mvcisback** [comment]
@alexeyignatiev new PR that takes care of the `.nv` attribute. Regarding the mapping, there is a slight problem I foresee.

`py-aiger` supports inputs and outputs having the same name. Internally this is done by wrapping inputs with the `Input` object. `id2obj` seems to point at both inputs and outputs, so this would cause an issue for such circuits.

**Comment by mvcisback** [comment]
@alexeyignatiev This is why I use to different `bidicts` for `py-aiger-cnf` 

- https://github.com/mvcisback/py-aiger-cnf/blob/master/aiger_cnf/cnf.py#L20

**Comment by alexeyignatiev** [comment]
I see. Well, okay, let it be the way you implemented it. Can I assume the names of the input variables will always be `"Input(name='var')"`? In this case, I could simply drop the unnecessary parts of the string. In either case, the PR is merged now. I am going to prepare version 0.1.4.dev20 reflecting your changes. Thanks!

**Comment by alexeyignatiev** [comment]
A major issue spotted: pip fails to install py-aiger-cnf (and so python-sat) for Python 2!

**Comment by mvcisback** [comment]
Uh oh! I wonder why this didn't show up before since `py-aiger` depends on `python 3.6+`.

The code seems to already be written to let `py-aiger` be an optional dependency. Perhaps it makes sense to set it as optional in `setup.py`?

**Comment by alexeyignatiev** [comment]
Yes, `py-aiger` was an optional dependency.

OK, thanks for fixing! I updated the version of PySAT. I am going to close the issue. Please, feel free to reopen if something can still be improved/fixed.

**Comment by alexeyignatiev** [comment]
Hi @mvcisback,

I have got one more issue and so reopen the discussion. See the code below:

```python
>>> import aiger
>>> from pysat.formula import CNF, IDPool
>>>
>>> x, y, z = aiger.atom('x'), aiger.atom('y'), aiger.atom('z')
>>> expr1 = ~(x | y) & z
>>> expr2 = ~expr1
>>>
>>> cnf1, cnf2, pool = CNF(), CNF(), IDPool()
>>> cnf1.from_aiger(expr1, vpool=pool)
>>> cnf2.from_aiger(expr2, vpool=pool)
>>>
>>> cnf1.clauses
[[2, 1, 3], [-2, -3], [-1, -3], [-3, -4, 5], [3, -5], [4, -5]]
>>>
>>> cnf2.clauses
[[2, 1, 6], [-2, -6], [-1, -6], [-6, -4, 7], [6, -7], [4, -7], [7, 8], [-7, -8]]
>>>
>>> for i in pool.id2obj:
...     print(i, pool.id2obj[i])
...
1 Input(name='y')
2 Input(name='x')
3 AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y')))
4 Input(name='z')
5 AndGate(left=AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))), right=Input(name='z'))
6 AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y')))
7 AndGate(left=AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))), right=Input(name='z'))
8 Inverter(input=AndGate(left=AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))), right=Input(name='z')))
>>>
>>> for o in pool.obj2id:
...     print(o, pool.obj2id[o])
...
Input(name='y') 1
Input(name='x') 2
AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))) 3
Input(name='z') 4
AndGate(left=AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))), right=Input(name='z')) 5
AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))) 6
AndGate(left=AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))), right=Input(name='z')) 7
Inverter(input=AndGate(left=AndGate(left=Inverter(input=Input(name='x')), right=Inverter(input=Input(name='y'))), right=Input(name='z'))) 8
```

As you can observe, `expr2` is the negation of `expr1`. And so it is quite natural to assume that `cnf1` and `cnf2` would share variables and clauses encoding the same gates if the same `IDPool()` was used. Ideally, I would like `cnf2` to have the same variables and clauses plus one *additional* variable for the negation of the output and the corresponding *additional* clauses.

However, this is not the case. And so aiger-cnf re-introduces fresh variables for the same gates even though the variable mapping is the same. The only variables shared are the input ones.

This issue looks quite important to me. Do you think this is fixable?

**Comment by mvcisback** [comment]
@alexeyignatiev 

This makes sense.

I think this should be possible, particularly if the negation doesn't change the structure of the circuit - as py-aiger is implemented this should be fine but in theory it could.

The problem is that py-aiger is currently dumb about the way it hashes things.

I think making it so structurally equivalent circuit hash the same way would fix this. I've been thinking about doing this for a while, so I can try it out and get back.

I can look sometime next week - CAV rebuttals are due Monday.

**Comment by alexeyignatiev** [comment]
Hi @mvcisback,

I believe conceptually this should be easy to do. A tuple (gate_type, *gate_inputs) completely defines a unique gate, which can be reused multiple times in a formula (multiple formulas). If you use this kind of hashing, then the corresponding variables will be reused as well.

Sure, feel free to do it when you have time. But, please, don't take too long. :)

**Comment by mvcisback** [comment]
@alexeyignatiev Yes, I actually pushed code a bit ago that does something similar, although I tried to use the hash of a `frozenset` rather than a tuple that way I can get commutativity.

**Comment by alexeyignatiev** [comment]
Sure, it is perfectly fine to use `frozenset` for that.

**Comment by mvcisback** [comment]
@alexeyignatiev I had some time and have updated the following packages:
-  `py-aiger`: Now version 4.0.0. Changes the hashing scheme.
- `py-aiger-cnf`: Now version 3.0.0

`py-aiger-cnf` just depends on the new version of `py-aiger`. Re-running the same code as before yields:

```python
In [1]: import aiger
   ...: from pysat.formula import CNF, IDPool
   ...:
   ...: x, y, z = aiger.atom('x'), aiger.atom('y'), aiger.atom('z')
   ...: expr1 = ~(x | y) & z
   ...: expr2 = ~expr1
   ...:
   ...: cnf1, cnf2, pool = CNF(), CNF(), IDPool()
   ...: cnf1.from_aiger(expr1, vpool=pool)
   ...: cnf2.from_aiger(expr2, vpool=pool)

In [2]:

In [2]: cnf1.clauses
Out[2]: [[1, 2, 3], [-1, -3], [-2, -3], [-3, -4, 5], [3, -5], [4, -5]]

In [3]: cnf2.clauses
Out[3]: [[1, 2, 3], [-1, -3], [-2, -3], [-3, -4, 5], [3, -5], [4, -5], [5, 6], [-5, -6]]
```

The new clauses `[5,6]` and `[-5, -6]` just encodes:

`5 implies -6` and `-5 implies -6`

as desired.

**Comment by alexeyignatiev** [comment]
Thanks, @mvcisback! That was quick! :)

**Comment by alexeyignatiev** [comment]
I am closing it now. Thanks again!
