### ISSUE TITLE
Cardinality for "all same"?

### ISSUE THREAD

**Issue by lolz0r** [pysathq/pysat#29]
Hi,
I'd like to add a clause to a formula indicating that I want a series of values to be "all the same", either all TRUE or all FALSE. 

How would one accomplish this?

**Comment by alexeyignatiev** [comment]
Hi @lolz0r,

This should be easy to do. The first thing that comes to my mind is to have a pairwise equality, i.e. given `n` variables, you add two clauses per each pair `(i, j)` of variables: `[[-i, j], [i, -j]]`. However, this would result in a **quadratic** number of clauses (on `n`).

```python
import itertools
from pysat.formula import CNF

def allsame_q(vars):
    """
        Here we assume that vars is an iterable of positive integers.
    """

    cnf = CNF()

    for i, j in itertools.combinations(vars, 2):
        cnf.append([-i, j])
        cnf.append([i, -j])

    return cnf
```

A better solution would be to consider two formulas `T` and `F` enforcing all variables to have a concrete constant value: either `1` or `0`, respectively. Each formula is a simple conjunction of unit-size clauses. And then you encode a disjunction `T v F` by introducing a pair of auxiliary variables. In this case, the number of clauses is **linear** on the number of variables.

```python
from pysat.formula import CNF

def allsame_l(vars):
    """
        Here we assume that vars is an iterable of positive integers.
    """

    cnf = CNF()
    t = max(vars) + 1  # fresh variable for T
    f = max(vars) + 2  # fresh variable for F

    # Tseitin-encoding T and F
    for v in vars:
        cnf.append([-t, v])
        cnf.append([-f, -v])
    cnf.append([t] + [-v for v in vars])
    cnf.append([f] + [v for v in vars])

    # final clause
    cnf.append([t, f])

    return cnf
```

Now, you can check the correctness by doing something like this:

```python
from pysat.solvers import Solver

# assume you have 10 variables:
cnf1 = allsame_q(range(1, 11))
with Solver(bootstrap_with=cnf1.clauses) as s:
    for m in s.enum_models():
        print(m)

# you should get:
[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

cnf2 = allsame_l(range(1, 11))
with Solver(bootstrap_with=cnf2.clauses) as s:
    for m in s.enum_models():
        print(m)

# you should get (notice each model assigns two additional variables 11 and 12):
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, -12]
[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, 12]
```
 
Observe that while the first solution uses a quadratic number of clauses the second one introduces two additional variables (which is perfectly fine but you should not forget about them). Hope this helps.

**Comment by lolz0r** [comment]
This is really great, perfect! Exactly what I was looking for. I really appreciate it. Thank you!

**Comment by alexeyignatiev** [comment]
No problem. :) I guess it makes sense to have something like a guide on what can be done with PySAT and how.
