### ISSUE TITLE
Variable mapping when using from_aiger

### ISSUE THREAD

**Issue by allrtaken** [pysathq/pysat#41]
Hi Alexey,

I want to convert an Aiger file with one Primary Output to CNF, and I found the from_aiger parameter in the CNF constructor. I wanted to know what mapping is used between the Primary Inputs, Latch Inputs of the Aiger file and variables of the CNF. I will need to modify the CNF later, for which I need to know the variables corresponding to the inputs and latches as well as the auxiliary vars.

Thanks!

**Comment by alexeyignatiev** [comment]
Hi Aditya,

Please, see an [example](https://pysathq.github.io/docs/html/api/formula.html#pysat.formula.CNF.from_aiger) in the API documentation. It should illustrate how to get the mapping. If you still have questions, feel free to ask here.

Best,
Alexey

**Comment by allrtaken** [comment]
Oops, missed that part in the docs -- thanks!
