### ISSUE TITLE
cannot install pysat cdf package

### ISSUE THREAD

**Issue by alexanderamadhan** [pysathq/pysat#42]
i have error while installing pysat cdf. the error message is shown below :

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\asus\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-0cqjz8ka\\pysatCDF\\setup.py'"'"'; __file__='"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-0cqjz8ka\\pysatCDF\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ASUS\AppData\Local\Temp\pip-install-0cqjz8ka\pysatCDF\pip-egg-info'
         cwd: C:\Users\ASUS\AppData\Local\Temp\pip-install-0cqjz8ka\pysatCDF\
    Complete output (5 lines):
    Building CDF for pysatCDF.
    running egg_info
    running build_src
    Cleaning CDF
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

please help me

**Comment by alexeyignatiev** [comment]
Hi @alexanderamadhan,

I guess you want to install a different package - [pysatCDF](https://github.com/pysat/pysatCDF). It has nothing to do with our work. :)

Best,
Alexey

**Comment by alexanderamadhan** [comment]
and i cant install pysat to, what a solve?
C:\Users\ASUS> pip install -U python-sat
Collecting python-sat
  Using cached python-sat-0.1.5.dev6.tar.gz (258 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\asus\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-nuyzolc7\\python-sat\\setup.py'"'"'; __file__='"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-nuyzolc7\\python-sat\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ASUS\AppData\Local\Temp\pip-install-nuyzolc7\python-sat\pip-egg-info'
         cwd: C:\Users\ASUS\AppData\Local\Temp\pip-install-nuyzolc7\python-sat\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ASUS\AppData\Local\Temp\pip-install-nuyzolc7\python-sat\setup.py", line 127, in <module>
        with chdir(solver):
      File "c:\users\asus\appdata\local\programs\python\python36\lib\contextlib.py", line 82, in __enter__
        return next(self.gen)
      File "C:\Users\ASUS\AppData\Local\Temp\pip-install-nuyzolc7\python-sat\setup.py", line 42, in chdir
        os.chdir(new_dir)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'cadical'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alexanderamadhan** [comment]
C:\Users\ASUS>pip install pysat
Collecting pysat
  Using cached pysat-2.1.0.tar.gz (171 kB)
Collecting requests
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Collecting lxml
  Using cached lxml-4.5.0-cp36-cp36m-win_amd64.whl (3.7 MB)
Collecting netCDF4
  Using cached netCDF4-1.5.3-cp36-cp36m-win_amd64.whl (3.1 MB)
Requirement already satisfied: xarray in c:\users\asus\appdata\local\programs\python\python36\lib\site-packages (from pysat) (0.15.0)
Collecting pandas<0.25,>=0.23
  Using cached pandas-0.24.2-cp36-cp36m-win_amd64.whl (8.8 MB)
Requirement already satisfied: numpy>=1.12 in c:\users\asus\appdata\local\programs\python\python36\lib\site-packages (from pysat) (1.18.1)
Requirement already satisfied: scipy in c:\users\asus\appdata\local\programs\python\python36\lib\site-packages (from pysat) (1.4.1)
Requirement already satisfied: matplotlib in c:\users\asus\appdata\local\programs\python\python36\lib\site-packages (from pysat) (3.1.3)
Collecting pysatCDF
  Using cached pysatCDF-0.3.0.tar.gz (1.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\asus\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-btsecrux\\pysatCDF\\setup.py'"'"'; __file__='"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-btsecrux\\pysatCDF\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ASUS\AppData\Local\Temp\pip-install-btsecrux\pysatCDF\pip-egg-info'
         cwd: C:\Users\ASUS\AppData\Local\Temp\pip-install-btsecrux\pysatCDF\
    Complete output (5 lines):
    Building CDF for pysatCDF.
    running egg_info
    running build_src
    Cleaning CDF
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alexeyignatiev** [comment]
Which package exactly do you want to install and why (`pysat`, `pysatCDF`, and `python-sat` are different projects with different goals).

**Comment by alexanderamadhan** [comment]
i'm sorry let me clear my self, i'm trying to install python-sat but i keep having this error

C:\Users\ASUS>pip install python-sat
Collecting python-sat
  Using cached python-sat-0.1.5.dev6.tar.gz (258 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\asus\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-coc96vxb\\python-sat\\setup.py'"'"'; __file__='"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-coc96vxb\\python-sat\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ASUS\AppData\Local\Temp\pip-install-coc96vxb\python-sat\pip-egg-info'
         cwd: C:\Users\ASUS\AppData\Local\Temp\pip-install-coc96vxb\python-sat\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ASUS\AppData\Local\Temp\pip-install-coc96vxb\python-sat\setup.py", line 127, in <module>
        with chdir(solver):
      File "c:\users\asus\appdata\local\programs\python\python37\lib\contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "C:\Users\ASUS\AppData\Local\Temp\pip-install-coc96vxb\python-sat\setup.py", line 42, in chdir
        os.chdir(new_dir)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'cadical'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alexeyignatiev** [comment]
So you mean you want to use Boolean satisfiability solvers in Python?

**Comment by alexanderamadhan** [comment]
yessss

**Comment by alexeyignatiev** [comment]
OK, since you use Windows, you may want to try to install the binary wheel distribution:
```
$ pip install python-sat==0.1.5.dev4
```

**Comment by alexanderamadhan** [comment]
yeah finally, thank you so much sir

**Comment by alexeyignatiev** [comment]
OK, good. I am closing it now.

**Comment by alexanderamadhan** [comment]
hi, i want to ask you about installation sat boolean again, if i use python version 3.8.2, can i install it?

**Comment by alexeyignatiev** [comment]
It depends on the system you are using (among other factors). If you use Windows then the only installable version for you at this point is `0.1.5.dev4`. In that case, try to install it using the command:

```
pip install python-sat==0.1.5.dev4
```

On Linux and MacOS you should be able to install the latest version:

```
pip install python-sat
```

Other installation instructions can be found [here](https://pysathq.github.io/installation.html).
