### ISSUE TITLE
[Win10 x64, Python 3.8.2] ImportError: DLL load failed while importing pycard: The specified module could not be found.

### ISSUE THREAD

**Issue by rtentser** [pysathq/pysat#43]
Hi there.

test.py:
`import pysat.card`

```
> python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pysat.card
  File "C:\Users\rtentser\AppData\Local\Programs\Python\Python38\lib\site-packages\pysat\card.py", line 99, in <module>
    import pycard
ImportError: DLL load failed while importing pycard: The specified module could not be found.
```

I use 0.1.5.dev4 (because more recent versions fail to install). Installed with pip.

**Comment by alexeyignatiev** [comment]
Hi @rtentser.

Unfortunately, I don't have a Windows machine to check that. Last time I tried, it worked fine. Do you know if you have the corresponding file? I mean can it be the case that the installer failed to copy it?

Alexey

**Comment by rtentser** [comment]
I have `pycard.cp38-win_amd64.pyd` in `Python38\Lib\site-packages`.

**Comment by alexeyignatiev** [comment]
OK, can you do something like
```
$ cd C:\Users\rtentser\AppData\Local\Programs\Python\Python38\lib\site-packages\
$ python -c 'import pycard'
```
?

**Comment by rtentser** [comment]
```
PS C:\Users\rtentser\AppData\Local\Programs\Python\Python38\lib\site-packages> python -c 'import pycard'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing pycard: The specified module could not be found.
```

**Comment by alexeyignatiev** [comment]
@rjungbeck, by any chance, do you any ideas? :)

**Comment by rtentser** [comment]
Installed [0.1.5.dev5](https://github.com/rjungbeck/pysat/releases/tag/pysat-v1.0.61) with same result.

**Comment by rjungbeck** [comment]
Does your system have \windows\system32\vcruntim140.dll and \windows\system32\vcruntime140_1.dll?

**Comment by rtentser** [comment]
No, just `vcruntime140_clr0400.dll`.

**Comment by rtentser** [comment]
I've installed Visual C++ Redistributable and yes, it's solved a problem. Thank you!

Maybe this dependency needs to be mention somewhere. Or maybe i need a new eyes,

**Comment by rjungbeck** [comment]
My (potentially wrong) expectation was, that UCRT (universal C runtime) is installed with Windows 10 automatically. It is on all my systems (but all of them are development machines with some version of Visual Studio installation).
