### ISSUE TITLE
How to fix 'ERROR: Command errored out with exit status 1:'

### ISSUE THREAD

**Issue by acs19qc** [pysathq/pysat#44]
I am trying to install pysat, but it keeps running error when building wheel for pysatCDF:

Requirement already satisfied: soupsieve>=1.2 in /anaconda3/lib/python3.7/site-packages (from beautifulsoup4->pysat) (1.8)
Building wheels for collected packages: pysatCDF
Building wheel for pysatCDF (setup.py) ... error
ERROR: Command errored out with exit status 1:
   command: //anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tg/v1qsdkmn5rg_dnwh0k2xtw280000gn/T/pip-install-6ssrpcun/pysatCDF/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/v1qsdkmn5rg_dnwh0k2xtw280000gn/T/pip-install-6ssrpcun/pysatCDF/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/tg/v1qsdkmn5rg_dnwh0k2xtw280000gn/T/pip-wheel-di7gnbw7
       cwd: /private/var/folders/tg/v1qsdkmn5rg_dnwh0k2xtw280000gn/T/pip-install-6ssrpcun/pysatCDF/

**Comment by alexeyignatiev** [comment]
There may be a package name confusion here. If you are interested in [PySAT](https://pysathq.github.io/) then simply follow the installation instructions there.
