### ISSUE TITLE
invalid number of variables

### ISSUE THREAD

**Issue by beskyfil** [pysathq/pysat#51]
Hello, not exactly sure if this is an issue, but
when I call
cnf = CNF('test.cnf')
cnf.nv
I get 19 as a result, i know its an invalid CNF because in preamble I state that there will be 50 vars.
Is that ok and I am supposed to feed CNF only with correct input?

What happens when i state in preamble 50 variables, but then in actual clauses only 30 variables are used?
Should i expect .nv to return 50 or 30?

Thank you in advance for answers

test.cnf:
p cnf 50  91 
 4 -18 19 0
3 18 -5 0

**Comment by alexeyignatiev** [comment]
Hi @beskyfil, that's not a bug. The parser checks the actual number of variables and clauses when parsing the file. This is the case for a few SAT solvers (e.g. those based on MiniSat). We decided to inherit this functionality in PySAT.
