### ISSUE TITLE
Directly Support MAX-SAT in library

### ISSUE THREAD

**Issue by zhou13** [pysathq/pysat#6]
Recently I need to solve some combinatorial problem for my project. I discover your pysat and it is super convenient for solving SAT problems! One feature I'd like to see is to directly support some prebuilt MaxSAT algorithms in your library (I understand you provide them in your examples but it is not very user-friendly).  Something like
```
>>> g = Glucose3()
>>> g.add_clause([-1, 2], weight=1)
>>> g.add_clause([-2, 3], weight=pysat.infinity)
>>> print g.solve(maxsat=pysat.FM)
```

**Comment by alexeyignatiev** [comment]
Hi @zhou13, first, I am glad the toolkit is helpful! Thank you for using it.

Regarding your suggestion, I am not sure this is feasible at this stage the way you suggest. Classes like `Glucose3` or `Solver` implement an interface to a SAT solver, which tackles the decision problem for CNF formulas. And so adding MaxSAT (or QBF) capabilities to a SAT solver is not in line with our initial ideas. The idea is to have a SAT oracle, which can be applied in the context of higher-level problem-solving (including MaxSAT). Having said that, we may think of implementing a separate module with problem-solving tools, which we could distinguish from the `examples` module.

Could you, please, tell me what kind of problems you have when working with the MaxSAT examples in PySAT? I would expect the following code to work well. Here I use the RC2 MaxSAT solver, which won both unweighted and weighted categories of the MaxSAT evaluation 2018:

https://maxsat-evaluations.github.io/2018/results/complete/unweighted/summary.html
https://maxsat-evaluations.github.io/2018/results/complete/weighted/summary.html

The RC2 solver is a part of PySAT and it is available from the `examples` module.

```python
>>> from pysat.examples.rc2 import RC2
>>> from pysat.formula import WCNF

>>> # here is the formula from your example
>>> wcnf = WCNF()
>>> wcnf.append([-1, 2], weight=1)
>>> wcnf.append([-2, 3])  # no weight means the clause is hard
>>>
>>> rc2 = RC2(wcnf, solver='g3')
>>> print rc2.compute()  # return a MaxSAT model
[-1, -2, -3]
>>> print rc2.cost
0  # the cost is zero because the formula is satisfiable
>>>
>>> # let's add another hard and soft clause to make it intersting
>>> # here we add the clauses directly to RC2 (not a WCNF formula)
>>> rc2.add_clause([-3])
>>> rc2.add_clause([1], weight=1)

>>> print rc2.compute()
[1, -2, -3]
>>> print rc2.cost
1
>>> # you can add more hard and soft clauses to RC2 and make more MaxSAT calls
>>> # note that the RC2 MaxSAT calls can be done incrementally,
>>> # i.e. there is no need to start it from scratch at every invocation
```

Please, let me know if this helps.

I am currently working on the documentation of the `examples` module. This takes time but I hope the use of the provided examples will be a bit easier to understand once the documentation is finished.

**Comment by zhou13** [comment]
Thanks @alexeyignatiev!  I will try that and let you know my result.

**Comment by alexeyignatiev** [comment]
Hi @zhou13. Is there any update? Should I close it?

**Comment by alexeyignatiev** [comment]
OK, I hope the solution I described above is sufficient and, thus, will close the issue.
