### ISSUE TITLE
`CardEnc.atmost` resets `vpool.top` when `len(lits) <= bound`

### ISSUE THREAD

**Issue by peitl** [pysathq/pysat#60]
As the title says, when attempting to enforce a trivial at-most constraint (the bound is greater than or equal to the number of literals), which is represented by the empty set of clauses, and when an IDPool is passed as a parameter, the IDPool's `.top` member is erroneously reset to `0`, causing subsequently created variables to overwrite existing ones.

While this issue can easily be worked around by checking whether the bound is trivial during encoding, it may still introduce nasty bugs when one relies on it.

Below is a minimal snippet that reproduces the bug.

```
from pysat.formula import IDPool
from pysat.card import CardEnc

vp = IDPool()
n = 20
b = 50
assert n <= b

lits = [vp.id(v) for v in range(1, n+1)]
top = vp.top

G = CardEnc.atmost(lits, b, vpool=vp)

assert len(G.clauses) == 0

try:
    assert vp.top >= top 
except AssertionError as e:
    print(f"\nvp.top = {vp.top} (expected >= {top})\n")
    raise e
```

**Comment by alexeyignatiev** [comment]
Right, that's a bug. Thanks for reporting.

**Comment by alexeyignatiev** [comment]
The latest [commit](https://github.com/pysathq/pysat/commit/6bcabdeabf75f5ce560b20635a71b60ed25ca109) should address this.
