### ISSUE TITLE
On Parsimonious Cardinality Encodings

### ISSUE THREAD

**Issue by allrtaken** [pysathq/pysat#64]
Hi Alexey,

I have been using PySAT for creating CNFs that I run counters or samplers on, and the different cardinality constraint encoding options of PySAT are especially useful. However, not all encodings preserve the number of solutions, some not even after projecting on original variables. I thought it would be useful to share with others (and maybe even integrate into PySAT somehow), information on which encodings are parsimonious and which are not, and which encodings are fastest wrt counting/sampling.

Equality constraints with bound > 1 (eg: enforce exactly 5 out of 10 variables should be true):
   Encodings that give correct count without projection: 7,8,1  (best to worst in terms of speed for D4 model counter)
   Encodings that give correct count when projecting on original variables: 7,8,6,3,2,1 (best to worst in terms of speed for ApproxMC)

Equality constraints with bound = 1  (eg: enforce exactly 1 out of 10 vars to be true)
   Encodings that give correct count without projection: 0,1,4,5,7,8
   Encodings that give correct count when projecting on original variables: 0 through 8 (9 doesn't give correct answer)
   Note: In terms of speed, solving just one exact-1 constraint is usually very fast so encoding doesn't matter much. However with multiple exact-1 constraints over overlapping sets of variables, I found that encodings 4 or 5 generally seemed to be the fastest for counting (YMMV). 

NB: I have not performed rigorous experiments to compare speed; this is meant more as 'rule of thumb' when trying to get a working prototype. I have consistently gotten correct answers when using encodings mentioned above for the respective purposes. It maybe possible to make other encodings give correct counts too somehow, but I was unable to find a way.

**Comment by alexeyignatiev** [comment]
Hi Aditya, thanks. It would be great if you could provide me with some examples illustrating this, so that I could see how to address this.

**Comment by alexeyignatiev** [comment]
Can you check [this](https://repl.it/@alexeyignatiev/parsimonious-cardenc) and tell me where the problem arises?

**Comment by allrtaken** [comment]
Hi Alexey,

Maybe I'm missing something completely obvious but in your script shouldn't the check for n==nums['native'] be performed for every value of 'b' in the for loop? Right now, it seems like the values in nums would be overwritten and only the values for b==nv would get checked. Ideally, in the case for equals, you can check if n==b at every step to be more sure.

**Comment by alexeyignatiev** [comment]
Yes, sure. That's a typo.

**Comment by allrtaken** [comment]
1) Thanks! So from what I can see, your results match with what I got for the projected case, as in line 13 you effectively project on the original variables. I got an incorrect answer for encoding number 9, while it works in your case, but I guess that can be explained because I believe it requires a specialized solver
2) As a non-expert, it was not easily apparent to me that encodings 0,4,5 do not work for bounds > 1. It would be great if it is possible to incorporate an exception in PySAT if those encodings are used with bounds larger than 1. I know it is mentioned in the docs, but when doing quick prototyping and checks it is easy to miss.
3) For bound > 1 encodings 1,7,8 give correct counts even if you do not project on the original variables as you do in line 13. This can be helpful if one is using model counter that does not support projection. Encodings 7,8 are especially fast and compact.
4) For bound =1 encodings 2,3,6 do not give correct counts if not projecting on original variables. Rest of the encodings work fine even if not projecting

**Comment by alexeyignatiev** [comment]
1. Yes, `native` cardinality constraints are handled properly only in MiniCard. Other solvers do not work with them.
2. Yes, this is mentioned in the API documentation. But I agree that it makes perfect sense to have an exception raised in this case. Thanks for the suggestion.
3. The "pairwise" encoding (1) uses the original variables only. So in this case, the projection does nothing. It is interesting to know that "modulo totalizer" and "k-modulo totalizer" give correct results even without projection. I am somewhat surprised given that they use auxiliary variables.
4. Thanks!

**Comment by starwarswii** [comment]
> 2. Yes, this is mentioned in the API documentation.

i thought for sure it didn't but i checked again, and you're right!
*"Note that the implementation of the pairwise, bitwise, and ladder encodings can only deal with AtMost1 constraints"*
[here, near the end](https://pysathq.github.io/docs/html/api/card.html#module-description)

that's pretty easy to miss.that line should definitely be bolded or something

**Comment by starwarswii** [comment]
@allrtaken your original post discusses `exactlyK` constraints. are there similar insights / how do they relate to `atMostK` and `atLeastK` constraints?

**Comment by allrtaken** [comment]
@starwarswii nothing very specific for amo/alo, but as a rule of thumb I would go for encodings 7,8 (totalizers) first as they are fast and work without projection.
