### ISSUE TITLE
PyPBLib PB to CNF encoder

### ISSUE THREAD

**Issue by vlastikw** [pysathq/pysat#65]
I'm trying to convert simple pb constraint to CNF but it seems not to work.

e.g. x1 + x2 + x3 .... = 1 always returns the same CNF regardless encoder used.

Attached my code.

If I use cardinality encoding it works for different encoders I get
different CNF output. Also attached example.

I assume that something is wrong with PBConfig that it ignores
PB_Encoder value set.

Describe the bug

PBLib converts PB constraint to CNF always the same way regardless encoder used i.e. PBConfig.PB_Encoder
Expected behavior

Expected output CNF should differ in variables and clauses not always the same.
To Reproduce

Conversion to CNF with cardinality encoder works as expected. Code for both to compare attached.
from pypblib import pblib
from pypblib.pblib import PBConfig, Pb2cnf
max = 129
lits=list(range(1,max))
wlits=[]
print(lits)
weights=[]
for x in lits:
weights.append(1)
wlits.append(pblib.WeightedLit(x, 1))

print("Number of weights %d" % len(weights))

pb_encoders=[pblib.PB_BDD,pblib.PB_SWC, pblib.PB_SORTINGNETWORKS, pblib.PB_ADDER, pblib.PB_BINARY_MERGE]

for x in pb_encoders:
print("Encoding PB %d" % (x))

config = PBConfig()
config.set_PB_Encoder(pblib.PB_BDD)
#print(config)

formula = []
pb2 = Pb2cnf(PBConfig())
max_var = pb2.encode_both(weights,lits, 1,1, formula, max)
print("Number of variables %d" % max_var)
print("Number of clauses %d" % len(formula) )

constr = pblib.PBConstraint(wlits, pblib.BOTH, 1)
aux_var = pblib.AuxVarManager(max)
formula = pblib.VectorClauseDatabase(config)
pb2cnf = pblib.Pb2cnf(config)
pb2cnf.encode(constr, formula, aux_var)
print("Number of variables %d" % aux_var.get_biggest_returned_auxvar() )
print("Number of clauses %d" % formula.get_num_clauses() )

from pysat import *
from pysat.pb import *
from pysat.card import *

lits=list(range(1,129))
print(lits)

for x in range(1,6):
print("Encoding PB %d" % (x))
cnf = PBEnc.equals(lits=lits, encoding=x)
print(cnf.clauses)

print("Number of variables %d" % cnf.nv)
print("Number of clauses %d" % len(cnf.clauses) )

print("****************************")

for x in range(0, 9):
print("Encoding SAT %d" % (x))
cnf = CardEnc.equals(lits=lits, encoding=x)
print(cnf.clauses)

print("Number of variables %d" % cnf.nv)
print("Number of clauses %d" % len(cnf.clauses) )

**Comment by alexeyignatiev** [comment]
Hi @vlastikw. I replied to your previous email. I believe the bug may appear in PyPBLib. If that is the case, there is nothing I can do on the side of PySAT. We could look into the source code of PyPBLib and see if this can be solved but I would not be able to update the PyPBLib package anyway. So it is best to contact the authors.

**Comment by vlastikw** [comment]
I've found repository for PyPBLib on github as well and created issue. Let's see if something happens.
https://github.com/rjungbeck/pypblib/issues/1
