### ISSUE TITLE
Why there are more variables (5-10) while the input is from 1-4 in PBEnc cardinality constraint?

### ISSUE THREAD

**Issue by ehsan-buet** [pysathq/pysat#66]
`cnf = PBEnc.geq(lits=[-1,-2,3,4], bound=2)`
`print(cnf.clauses)`

Output: [[5],
 [-1, -6],
 [-2, -6],
 [-1, -2, -7],
 [7, -8],
 [6, 3, -8],
 [7, 3, -9],
 [9, -10],
 [8, 4, -10],
 [10]]

**Comment by alexeyignatiev** [comment]
Most of the pseudo-Boolean and cardinality encodings introduce auxiliary variables. This is the way they operate.
