### ISSUE TITLE
How to append negated clause to the formula?

### ISSUE THREAD

**Issue by m-kru** [pysathq/pysat#67]
Clauses passed to the formula must have logical disjunction form. Lets assume I have following clause in conjunction form `1 and -2 and -3`, using the De Morgan's laws I can convert it to `-[-1, 2, 3]`. However is it possible to add negated clause to the formula? What is the standard procedure in such case?

**Comment by expxlc** [comment]
The standard procedure is to use [Tseitin transformation](https://en.wikipedia.org/wiki/Tseytin_transformation) that handles _non-clausal parts_ of the formula.
In your case, however, you don't need to apply Tseitin transformation - simply add 3 unit-size clauses: `[1]`, `[-2]`, and `[-3]`.

**Comment by alexeyignatiev** [comment]
The standard procedure is to use [Tseitin transformation](https://en.wikipedia.org/wiki/Tseytin_transformation) that handles _non-clausal parts_ of the formula.
In your case, however, you don't need to apply Tseitin transformation - simply add 3 unit-size clauses: `[1]`, `[-2]`, and `[-3]`.

**Comment by m-kru** [comment]
Tseitin-encoding is currently not supported by the pysat, isn't it?

**Comment by alexeyignatiev** [comment]
It is supported by the functionality of `py-aiger`. See the documentation [here](https://pysathq.github.io/docs/html/api/formula.html#pysat.formula.CNF.from_aiger). Using `py-aiger`, you can write down arbitrary Boolean formulas and encode them to `CNF` through the AIG translation.
