### ISSUE TITLE
LSU found_optimal() is wrong after interrupting the solver

### ISSUE THREAD

**Issue by daniel-vos** [pysathq/pysat#74]
I noticed that after early stopping the LSU MaxSAT solver the resulting calls to `found_optimal()` would always return True. I think the function should be changed from:
```python
    def found_optimum(self):
        """
            Checks if the optimum solution was found in a prior call to
            :func:`solve`.

            :rtype: bool
        """

        return self.oracle.get_status() is not None
```

To something like:

```python
    def found_optimum(self):
        """
            Checks if the optimum solution was found in a prior call to
            :func:`solve`.

            :rtype: bool
        """

        oracle_status = self.oracle.get_status()
        if oracle_status is None:
            return False
        
        # If the last call was unsatisfiable that means that no better
        # solution is possible hence it is optimal.
        return not oracle_status
```

I was not 100% sure this is correct so I did not make a pull request. Thanks again for all your work on the project!

**Comment by daniel-vos** [comment]
Or I'm just interrupting the solver wrong.... After calling interrupt() everything works. Sorry!

**Comment by alexeyignatiev** [comment]
It's good to know that it is working. But I am afraid I don't understand what was wrong in the first place. Can you elaborate a bit more?
