### ISSUE TITLE
Improved Sequential Counters for atmost/atleast/equals

### ISSUE THREAD

**Issue by ahealy0** [pysathq/pysat#75]
Great library for experimenting with SAT solvers -- thank you.

I believe the 'seqcounter' implementation of atmost/atleast/equals can be improved substantially by following Knuth's presentation of Sinz' approach, rather than Sinz' original paper (see below).

Specifically, the 'seqcounter' implementation of atmost(lits, r) seems very wasteful when r is very large (i.e., close to len(lits)). Similarly, the implementation of atleast(lits, r) creates a surprisingly large number of clauses when r is small. (Together, these mean that equals(lits, r) is not very useful when 'lits' contains many variables.)

It *appears* that atmost() is directly implementing the approach from this paper:
https://www.carstensinz.de/papers/CP-2005.pdf
which yields a CNF with 2*n*r + n - 3*r - 1 clauses. 

But note how this grows like n^2 if r is very close to n (e.g., r = n - 5).

I don't believe this quadratic blow-up in clauses is inherent to the 'sequential counter' approach. For example, see formulas (18) & (19) (on p. 8) of Knuth's "Fascicle 6":
https://ptgmedia.pearsoncmg.com/images/9780134397603/samplepages/9780134397603.pdf

Ostensibly, he's also implementing Sinz' "sequential counter", but he's doing it in a way that's somewhat more careful and only requires (n-r-1)*r + (n-r)(r+1) new clauses. (Note how this is still O(n), for example, when r = n - 5.)

As a concrete example, if n = 100 and r = 95, Knuth's formulation works out to a very manageable 860 clauses. And yet:
```
cnf = pysat.card.CardEnc.atmost(list(range(1, 101)), 95)
print(len(cnf.clauses))
18814
```
(i.e., more than 21x more clauses than necessary (!) and, of course, this phenomenon only gets worse as n gets larger.)

It would be great to update this implementation of seqcounter to use the formulas from Knuth (or something similar)!

Regards,

Alex Healy

**Comment by alexeyignatiev** [comment]
Hi Alex,

Thank you for letting me know. It would be indeed nice to improve the implementation of sequential counters if that is possible. I need to look into the fascicle and try to understand what Knuth's version of the encoding does and whether or not something similar has been already done in other cardinality encodings. I will try to find time for this.

Best,
Alexey

**Comment by ahealy0** [comment]
Hi Aleksey,

Knuth doesn't say too much about this encoding in the text on p. 8, although he does spell out the details explicitly. (There's a bit more detail in the solution to exercise 26, but neither the exercises nor the solutions are the PDF link I sent.) That being said, what he's doing is fundamentally the same as the Sinz paper -- he's just being careful to not include variables/clauses that are superfluous.

Here's what I mean . . . 

The "easy" way to implement a sequential counter to count up to r would be to create a finite state machine with n 'layers' of r states each (for O(n*r) states total, arranged in a rectangular array) where each state s_ij represents the predicate "the number of 1s in x_1, . . ., x_j is at least i" (which can be implemented through O(n*r) clauses). Now, if you think about the states s_{1,2}, s_{1,3}, . . ., s_{1,r}, they can never be reached -- you can't read 1 bit and observe more than one 1! In general, the states s_ij where i < j are pointless, for the same reason (and any clauses that include them can be eliminated/simplified). Essentially, all that's happening in Knuth's formulation is that he's being careful about these corner cases, and he ends up with an array that looks like a parallelogram (of size (n-r)*r), rather than a rectangle (of size n*r). As a result, it's much more efficient (in terms of variables/clauses) when r is close to n.

Now, with the current implementation, a decent SAT solver will probably eliminate all the extraneous variables/clauses through unit-propagation, but it's still seems very wasteful to call atmost(...) and get a CNF with millions of clauses, only to then force the solver to clean up the mess. Besides, it's nice to be able to print out the number of clauses of the CNF and have it mean something. ;-)

In case it's helpful, here's my implementation of the formulas from Knuth:

```
def atMostN(X, n):
        # Output CNF clauses that ensure that no more than n of 
        # the literals in (the list) X are true
        # See Knuth: formulas (18) and (19)
        result = []
        S = [sat.newVars(len(X) - n) for k in range(n)]
        for j in range(0, len(X)-n):
            result.append([-X[j], S[0][j]])
            for k in range(0, n):
                if k < n-1:
                    if j < len(X) - n - 1:
                        result.append([-S[k][j], S[k][j+1]])
                    result.append([-X[j+k+1], -S[k][j], S[k+1][j]]) 
                else:
                    if j < len(X) - n - 1:
                        result.append([-S[k][j], S[k][j+1]]) 
                    result.append([-X[j+k+1], -S[k][j]]) 
        return result
```
This can probably be made a bit more efficient and/or more pythonic, but my primary goal was correctness.

Best,

Alex

**Comment by alexeyignatiev** [comment]
Hi Alex,

OK, I see what you mean. Essentially, a large number of variables and clauses in the original implementation are redundant. I will update our implementation following Knuth's formulation. Thank you for this!

Best, 
Alexey

**Comment by alexeyignatiev** [comment]
Hi Alex, I have finally got a chance to implement these changes - sorry for taking this long. The improved `'seqcounter'` encoding is in the latest version of the toolkit (0.1.7.dev2).

**Comment by ahealy0** [comment]
Looks good -- thanks!

**Comment by alexeyignatiev** [comment]
OK, then I am closing it for now.
