### ISSUE TITLE
Documentation example on Optux needs "mus" instead of m in loop variable

### ISSUE THREAD

**Issue by arjay55** [pysathq/pysat#77]
The example of using OptUx in python code needs for `m`, which is loop variable to be changed to `mus`. The example is now below:

from pysat.examples.optux import OptUx
from pysat.formula import WCNF

if __name__ == "__main__":
    wcnf = WCNF(from_file='formula_ex.dimacs.xz')

    with OptUx(wcnf) as optux:
        for mus in optux.enumerate():
            print('mus {0} has cost {1}'.format(mus, optux.cost))

**Comment by alexeyignatiev** [comment]
Thanks for reporting on the typo. I pushed a fix.
