### ISSUE TITLE
1.FM MaxSAT algorithm bug with WCNF and atms. 2. Fm.model issue.

### ISSUE THREAD

**Issue by Vikseko** [pysathq/pysat#80]
1. FM algorithm always wants WCNFPlus as input instead of regular WCNF. This causes an error with the atms attribute. 
2. For RC2, rc.model returns a list with the model, but for FM model, this is an object of the filter type, which needs to be additionally transformed into the list.

**Comment by alexeyignatiev** [comment]
Thanks for reporting. I will fix this when there is time (if this happens at some point...).

**Comment by alexeyignatiev** [comment]
This should be fixed in version 0.1.7.dev3. I am closing the issue.
