### ISSUE TITLE
Minimal satisfiability solver

### ISSUE THREAD

**Issue by migueltorrescosta** [pysathq/pysat#82]
Are any of the solvers optimized for minimal solutions, in the sense of minimizing the amount of literals set to true? I was considering something similar to this modification of pycosat: https://github.com/ContinuumIO/pycosat/pull/39

**Comment by haz** [comment]
Couldn't you just run maxsat with -1 weights on positive literals?

**Comment by alexeyignatiev** [comment]
@migueltorrescosta, a possible solution would be indeed the one suggested by @haz. Alternatively, a couple of solver we have in PySAT should always respect the polarities you set using `set_phases()`. See the documentation on [how this can be done](https://pysathq.github.io/docs/html/api/solvers.html#pysat.solvers.Solver.set_phases).

**Comment by migueltorrescosta** [comment]
Yes, that is ideal. Thank you for the prompt reply!
