### ISSUE TITLE
build breaks on macOS with case-insensitive file system

### ISSUE THREAD

**Issue by ott2** [pysathq/pysat#84]
[macos-patch.txt](https://github.com/pysathq/pysat/files/6631857/macos-patch.txt)
The cadical patches move some files around. On macOS 11.4 with the standard file system (which is case-insensitive) the system clang C++ compiler (version 12.0.5) then ends up trying to include the file VERSION verbatim via a system header file, which fails. Building pysat is therefore not working on recent macOS with current development tools.

To fix this, I modified `solvers/patches/cadical.patch` by replacing the line
``+VERSION="`cat `VERSION`"``
with
``+VERSION="`cat VERSION.txt`"``
and added the line
``        ('VERSION', 'VERSION.txt'),``
to the list in `to_move` in the file `solvers/prepare.py`.

There is probably a more canonical way to do this than editing patches, but this was the smallest change I found which achieved my goal of installing pysat.

(I do not know why the `#include <version>` in the system header files ends up including a local file as though it was `#include "version"`, but perhaps the pysat build system has redefined the search paths, this is a clang thing, or the standards have changed from when I last read them.)

**Comment by alexeyignatiev** [comment]
Thank you, @ott2. I will look into this. I've got a question though: why do you try to compile it? Doesn't the precompiled binary wheel work for you?

**Comment by alexeyignatiev** [comment]
This should be fixed now in version 0.1.7.dev4.

**Comment by ott2** [comment]
> Thank you, @ott2. I will look into this. I've got a question though: why do you try to compile it? Doesn't the precompiled binary wheel work for you?

I was just trying to do `pip3 install python-sat` and it was trying to compile, and failing. Thanks for looking into this so quickly.

**Comment by alexeyignatiev** [comment]
That's weird because PyPI should have it precompiled for all the major versions of Python, unless you are using M1.

**Comment by alexeyignatiev** [comment]
Anyway, I am closing it now as the issue should be resolved now.
