### ISSUE TITLE
Installing python-sat vs Importing pysat

### ISSUE THREAD

**Issue by migueltorrescosta** [pysathq/pysat#85]
The app is installed via `pip install python-sat`, but used as `import pysat`. This generates confusion since there is a completely unrelated [pysat package](https://pypi.org/project/pysat/) .
- Was there a motive for naming the package differently from when it is imported and installed?
- Is it feasible to allow it to be imported as `python-sat`, and eventually drop support of `import pysat`, for naming consistency?
There are a few [good reasons to name a package differently than their import name](https://stackoverflow.com/questions/54886143/why-are-some-python-package-names-different-than-their-import-name) , mostly due to legacy reasons (i.e. You want to install `yaml2` but use it as `import yaml` since the interface is the same as the first version), but I am confused as to why do that with `python-sat`

**Comment by alexeyignatiev** [comment]
Thanks for the comment, @migueltorrescosta.
A careful user should not get confused as the [installation page](https://pysathq.github.io/installation.html) gives the exact commands to be used for installing the package. The [API description](https://pysathq.github.io/docs/html/index.html) is quite elaborate too and should give an idea of how the toolkit should be used.
The name of the toolkit is **PySAT** and this was chosen intentionally when submitting the paper to SAT 2018, i.e. *before* the [PyPI package](https://pypi.org/project/python-sat/) was created. The name is not going to change as I don't think there is any major issue except for potentially some minor confusion.

**Comment by alexeyignatiev** [comment]
Closing.
