### ISSUE TITLE
invalid cardinality encoding parameters

### ISSUE THREAD

**Issue by psaikko** [pysathq/pysat#87]
Hi, it is currently possible to get some unexpected/non-obvious behavior with bad combinations of cardinality encoding types and bounds -- specifically with the pairwise, bitwise, and ladder encodings.

For example
`CardEnc.equals([1,2,3,4], bound=2, top_id=4, encoding=EncType.ladder)`
returns an empty formula. 

Perhaps more misleading is that 
`CardEnc.equals([1,2,3,4], bound=3, top_id=4, encoding=EncType.pairwise)`
returns a non-empty formula (the pairwise encoding for >=3)

In the interests of user-friendliness and accessibility I would suggest raising a suitably descriptive exception when trying to use CardEnc incorrectly.

**Comment by alexeyignatiev** [comment]
Hi @psaikko,

Thanks for raising this. The pairwise, bitwise and ladder encodings support only AtMost1 constraints as stated in the documentation. But you are right that PySAT should say something if a user tries to apply them with other bounds. Version `0.1.7.dev9` aims at solving this issue by raising an exception `UnsupportedBound(encoding, bound)`. Hopefully, this should suffice. The current version also fixes a couple of other minor issues related to cardinality constraint handling.

Alexey

**Comment by psaikko** [comment]
Hi @alexeyignatiev 

That's great to hear! Thanks for your work on PySAT, it has been very useful for prototyping work.

Paul

**Comment by alexeyignatiev** [comment]
Hi Paul,

I am glad if it helps other people do prototyping as it does help me! Please feel free to create more issue reports if you spot any other problems.

Thanks,
Alexey

**Comment by psaikko** [comment]
Just tried out `0.1.7.dev9`, there remains a problem with the "n - 1" case for equality constraints with pairwise, bitwise and ladder encodings:

For example `CardEnc.equals([1,2,3,4], bound=3, top_id=4, encoding=EncType.pairwise)` is missing the "<=" clause `[-1,-2,-3,-4]` and allows `[1,2,3,4]` as a satisfying assignment.

**Comment by alexeyignatiev** [comment]
Hm, that's strange. This is what I get:
```python
>>> cnf = CardEnc.equals([1, 2, 3, 4], bound=3, encoding=EncType.pairwise)
>>> print(cnf.clauses)
[[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4], [-1, -2, -3, -4]]
```
Are you sure you have updated? Because this is exactly the other issue `0.1.7.dev9` was supposed to fix.

**Comment by psaikko** [comment]
After installing PySAT in a fresh virtualenv I get the expected result. I had updated to `0.1.7dev9` but seem to have corrupted my install somehow. Sorry for the inconvenience.
