### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pysathq/pysat#88]
Problem
---------
On aarch64, pip install pysat builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install pysat should download the wheels from pypi

@alexeyignatiev, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by alexeyignatiev** [comment]
Thank you, @odidev! I am going to merge the PR.

**Comment by alexeyignatiev** [comment]
I am closing this issue. @odidev, feel free to reopen in case something is still wrong.
