### ISSUE TITLE
Unable to compile solvers with MSVC because of wrong path resolution

### ISSUE THREAD

**Issue by S0mbre** [pysathq/pysat#92]
I am unable to install on my Win 10 machine due to MSVC (Build Tools 14) build errors when trying to resolve includes in each solver directory. For example, trying to build `cadical` produces this error:
> building 'pysolvers' extension
> ...
> c:\_PROG_\Projects\pysat-master\solvers\cadical\file.hpp(96): error C3861: getc_unlocked: unknown identifier

If I remove `cadical` from `to_install` in `setup.py`, I still get errors for other solvers:
> solvers/glucose30/core\Solver.cc(32): fatal error C1083: Unable to open include file: mtl/Sort.h: No such file or directory

Which is not surprising because `solver.cc` resides in `...\solvers\glucose30\core\`, whereas `mtl` and `utils` directories are separately located in `...\solvers\glucose30\`, so  `solver.cc` doesn't see the includes.

The same happens with `glucode41` and all the other solvers. My guess is that the `to_move` list in `prepare.py` is not configured correctly, so the subdirectories are not copied into the `core` directories of each solver.

See attached: prepare.py + setup.py

[prepare.zip](https://github.com/pysathq/pysat/files/7369482/prepare.zip)

**Comment by alexeyignatiev** [comment]
No, you can! Try to do: `pip install python-sat`.

**Comment by S0mbre** [comment]
Oops! Thanks for this, didn't see any reference to PySAT being on PyPI. Should probably update README... 
BTW does the wheel include all the SAT solvers?

**Comment by alexeyignatiev** [comment]
Well, it should be mentioned [here](https://pysathq.github.io/installation.html). Regarding SAT solvers, unless I am missing something, all the SAT solvers should be available on Windows too.

**Comment by S0mbre** [comment]
OK thanks again! One last question: do you think a [problem like this](https://stackoverflow.com/questions/69625906/generate-cnf-from-boolean-expression) can be solved with SAT and specifically PySAT? Need help where to start...

**Comment by may1066** [comment]
I get a very similar problem with the includes not being found when using pip install python-sat 

>   C:\Users\user\AppData\Local\Temp\pip-install-mcm1w8lv\python-sat_df06820ba81142d08bddced4adc6b98f\solvers\gluecard30/core/Solver.h(32): fatal error C1083: Cannot open include file: 'mtl/Vec.h': No such file or directory

**Comment by alexeyignatiev** [comment]
@may1066, what system are you using? As I mentioned above, PySAT has a number of binary wheels precompiled for Windows.

**Comment by may1066** [comment]
Sorry, I was using windows 10 with python 3.6
I updated python to 3.9 and it now seems to be working (I noticed that issue #7 mentioned that updating to python 3.7 solved some of the problems they were having)
Thank you!

**Comment by alexeyignatiev** [comment]
@may1066, it's good to know that it works now. Although I am not sure why exactly updating Python to version 3.9 helped. :)

**Comment by mueller55** [comment]
I am using Windows 10 with Python 3.10.4. When I type pip install python-sat, it does invoke wsl.exe and the C++ compiler. What do I need to do to simply install the binaries?

**Comment by alexeyignatiev** [comment]
I believe your 64bit Intel processor should still belong to the amd64 family. Note that we currently don't have builds for Python 3.10. However, we do have a build for Python 3.9. You may want to give it a try instead.
