### ISSUE TITLE
Missing self.atm1 in pysat.examples.fm.FM (0.1.7.dev12)?

### ISSUE THREAD

**Issue by scoopergit** [pysathq/pysat#95]
In 0.1.7.dev12, initializing pysat.examples.fm.FM with a WCNF throws an exception looking for self.atm1.  It looks like self.atm1 only gets initialized when using a WCNFPlus.  Initializing self.atm1 to None seems to fix it.

**Comment by alexeyignatiev** [comment]
Thank you, @scoopergit. This should be fixed by the [latest commit](https://github.com/pysathq/pysat/commit/1c1dd0aebe077ca72ca743af4283a46bccf88bf9).

**Comment by scoopergit** [comment]
Thanks for the quick fix!
